import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {ConnectionController} from '../src/controller.mjs';
import {historyWindow} from '../src/answer-policy.mjs';
import {ConversationArchive} from '../src/conversation-archive.mjs';

const hash=text=>createHash('sha256').update(text).digest('hex');
const answerCalls=f=>f.calls.filter(input=>!input.startsWith('NOTEWORK_CONVERSATION_STRUCTURE_V1'));
function structureResponse(input){const data=JSON.parse(input.split('\nDATA_JSON\n')[1]);return JSON.stringify({cards:data.cards.map(card=>({id:card.id,parentId:null,relation:'start',topic:'Synthetic conversation'}))});}
function fixture({count=2}={}) {
  const contents=new Map();const files=new Map();const folders=new Map();const tags=new Map();const calls=[];const reads=[];
  for(let index=0;index<count;index++){const path=count===2?'Research/'+(index===0?'a':'b')+'.md':'Research/note-'+index+'.md';const content=count===2?(index===0?'uniquealpha grounded evidence.':'uniquebeta grounded evidence.'):'Topic '+index+' grounded evidence.';contents.set(path,content);files.set(path,{path,stat:{size:Buffer.byteLength(content),mtime:1}});tags.set(path,['#research']);}
  const vault={getName:()=> 'Synthetic history privacy',getMarkdownFiles:()=>[...files.values()],getAbstractFileByPath:path=>files.get(path)||folders.get(path),cachedRead:async file=>contents.get(file.path),read:async file=>{reads.push(file.path);return contents.get(file.path);},createFolder:async path=>{const folder={path,children:[]};folders.set(path,folder);return folder;},create:async(path,content)=>{const file={path,stat:{size:Buffer.byteLength(content),mtime:1}};files.set(path,file);contents.set(path,content);return file;},process:async(file,fn)=>{const content=fn(contents.get(file.path));contents.set(file.path,content);return content;}};
  const provider={async generate(input){calls.push(input);if(input.startsWith('NOTEWORK_CONVERSATION_STRUCTURE_V1'))return structureResponse(input);return ['PRIVATE_NOTE_A_ANSWER','ANSWER_B_INHERITS_A','LATEST_ANSWER'][Math.min(answerCalls({calls}).length-1,2)];}};
  const archive=new ConversationArchive({vault,idFactory:()=> 'history-conversation'});
  const controller=new ConnectionController({providers:{chatgpt:provider},jev:{},secrets:{},vault,getTags:file=>tags.get(file.path)||[],settings:{mode:'chatgpt',scope:{tags:['#research']}},saveSettings:async()=>{},archive});controller.set({model:'synthetic-model',models:[{id:'synthetic-model'}],authenticated:true,connection:'catalog-confirmed',verified:true});
  const ask=async draft=>{controller.set({draft,consent:true});await controller.ask();await controller.mapPromise;};
  return{controller,vault,contents,files,tags,calls,reads,ask,archive};
}

test('unchanged lexical evidence retains prior assistant context with persisted full source lineage',async()=>{const f=fixture();await f.ask('uniquealpha');const original=f.controller.state.messages[1].content;assert.match(f.controller.state.messages[1].sources[0].contentHash,/^[a-f0-9]{64}$/);await f.ask('uniquebeta');assert.ok(answerCalls(f)[1].includes('PRIVATE_NOTE_A_ANSWER'));assert.deepEqual(f.controller.state.messages[3].contextSources.map(source=>source.path).sort(),['Research/a.md','Research/b.md']);assert.equal(f.controller.state.messages[1].content,original);});
test('removing an include tag prevents retransmission of an earlier answer derived from that note',async()=>{const f=fixture();await f.ask('uniquealpha');f.tags.set('Research/a.md',[]);await f.ask('uniquebeta');assert.equal(f.calls.length,4);assert.equal(answerCalls(f).length,2);assert.deepEqual(f.controller.state.sources.map(source=>source.path),['Research/b.md']);assert.ok(!answerCalls(f)[1].includes('PRIVATE_NOTE_A_ANSWER'));assert.ok(answerCalls(f)[1].includes('uniquealpha'));assert.deepEqual(f.controller.state.messages[3].contextSources.map(source=>source.path),['Research/b.md']);});
test('deleted source notes are omitted from prior assistant context while original archived turns remain intact',async()=>{const f=fixture();await f.ask('uniquealpha');f.files.delete('Research/a.md');await f.ask('uniquebeta');assert.ok(!answerCalls(f)[1].includes('PRIVATE_NOTE_A_ANSWER'));assert.equal(f.controller.state.messages[1].content,'PRIVATE_NOTE_A_ANSWER');});
test('same-size and same-mtime edits invalidate prior answer evidence using actual content hashes',async()=>{const f=fixture();await f.ask('uniquealpha');const previous=f.contents.get('Research/a.md');const updated=previous.replace('uniquealpha','changedtext');assert.equal(updated.length,previous.length);f.contents.set('Research/a.md',updated);await f.ask('uniquebeta');assert.ok(!answerCalls(f)[1].includes('PRIVATE_NOTE_A_ANSWER'));assert.equal(f.files.get('Research/a.md').stat.mtime,1);});
test('source lineage excludes descendant answers even after the original note falls outside the recent message window',async()=>{const f=fixture();await f.ask('uniquealpha');for(let index=0;index<8;index++)await f.ask('uniquebeta');assert.ok(!historyWindow(f.controller.state.messages).some(message=>message.id===f.controller.state.messages[1].id));assert.ok(f.controller.state.messages.at(-1).contextSources.some(source=>source.path==='Research/a.md'));f.tags.set('Research/a.md',[]);await f.ask('uniquebeta');const sent=answerCalls(f).at(-1);assert.equal(f.calls.length,20);assert.equal(answerCalls(f).length,10);assert.ok(!sent.includes('PRIVATE_NOTE_A_ANSWER'));assert.ok(!sent.includes('ANSWER_B_INHERITS_A'));assert.ok(!sent.includes('LATEST_ANSWER'));assert.deepEqual(f.controller.state.messages.at(-1).contextSources.map(source=>source.path),['Research/b.md']);});
test('legacy assistant turns without proven lineage are displayed locally but omitted from the outgoing history',async()=>{const f=fixture();const contextKey=f.controller.contextKey();f.controller.set({messages:[{id:'u-legacy',role:'user',content:'Prior user question',contextKey},{id:'a-legacy',role:'assistant',content:'UNKNOWN_OLD_ASSISTANT_CONTENT',contextKey,sources:[{path:'Research/a.md',contentHash:hash(f.contents.get('Research/a.md'))}]}]});await f.ask('uniquebeta');assert.ok(!f.calls[0].includes('UNKNOWN_OLD_ASSISTANT_CONTENT'));assert.ok(f.calls[0].includes('Prior user question'));assert.equal(f.controller.state.messages[1].content,'UNKNOWN_OLD_ASSISTANT_CONTENT');});
test('saved and reopened valid source lineage retains continuity and still rejects later source edits',async()=>{const f=fixture();await f.ask('uniquealpha');const saved=await f.controller.saveConversation();f.controller.newConversation();await f.controller.loadConversation(saved.id);assert.equal(f.controller.state.messages[1].contextSources[0].path,'Research/a.md');await f.ask('uniquebeta');assert.ok(answerCalls(f)[1].includes('PRIVATE_NOTE_A_ANSWER'));f.contents.set('Research/a.md','Changed after reopening.');await f.ask('uniquebeta');assert.ok(!answerCalls(f)[2].includes('PRIVATE_NOTE_A_ANSWER'));assert.ok(!answerCalls(f)[2].includes('ANSWER_B_INHERITS_A'));});
test('saturated lineage resets assistant context within the 64-source bound instead of losing provenance',async()=>{const f=fixture({count:65});const contextKey=f.controller.contextKey();const references=[...f.contents].map(([path,content])=>({path,contentHash:hash(content)}));f.controller.set({messages:[{id:'u-old',role:'user',content:'Previous question',contextKey},{id:'a-old',role:'assistant',content:'OVER_BUDGET_HISTORY',contextKey,sources:[references[0]],contextSources:references.slice(0,64)}]});const result=await f.controller.boundedHistory({contextKey,scope:f.controller.effectiveScope(),proof:{},sources:[references[64]]});assert.deepEqual(result.history,[{role:'user',content:'Previous question'}]);assert.deepEqual(result.contextSources,[references[64]]);assert.equal(f.reads.length,0);});
test('invalid hashes and incomplete inherited source coverage never authorize an old assistant turn',async()=>{const f=fixture();const contextKey=f.controller.contextKey();const reference={path:'Research/a.md',contentHash:hash(f.contents.get('Research/a.md'))};f.controller.set({messages:[{id:'u-old',role:'user',content:'Previous question',contextKey},{id:'a-old',role:'assistant',content:'BAD_HASH_HISTORY',contextKey,sources:[reference],contextSources:[{...reference,contentHash:'invalid'}]},{id:'a-missing',role:'assistant',content:'MISSING_LINEAGE_HISTORY',contextKey,sources:[reference],contextSources:[{path:'Research/b.md',contentHash:hash(f.contents.get('Research/b.md'))}]}]});await f.ask('uniquebeta');assert.ok(!f.calls[0].includes('BAD_HASH_HISTORY'));assert.ok(!f.calls[0].includes('MISSING_LINEAGE_HISTORY'));});
test('a retrieved note leaving scope during fresh validation stops before any model request',async()=>{const f=fixture();f.vault.read=async file=>{f.tags.set(file.path,[]);return f.contents.get(file.path);};await f.ask('uniquealpha');assert.equal(f.calls.length,0);assert.match(f.controller.state.status,/selected scope/);assert.equal(f.controller.state.messages.length,0);});
test('a late source mutation after history validation stops before transmitting either current or prior evidence',async()=>{const f=fixture();await f.ask('uniquealpha');let seen=0;f.vault.read=async file=>{if(file.path==='Research/a.md'&&++seen===2)f.contents.set(file.path,'Changed immediately before transmission.');return f.contents.get(file.path);};await f.ask('uniquebeta');assert.equal(f.calls.length,2);assert.equal(answerCalls(f).length,1);assert.match(f.controller.state.status,/conversation source changed/);});
test('stopping during a history-source read prevents a late model request',async()=>{const f=fixture();await f.ask('uniquealpha');let finish;let started;const begun=new Promise(resolve=>started=resolve);f.vault.read=file=>{if(file.path==='Research/a.md'){started();return new Promise(resolve=>finish=()=>resolve(f.contents.get(file.path)));}return Promise.resolve(f.contents.get(file.path));};const pending=f.ask('uniquebeta');await begun;f.controller.stop();finish();await pending;assert.equal(f.calls.length,2);assert.equal(answerCalls(f).length,1);assert.equal(f.controller.state.busy,false);assert.equal(f.controller.state.messages.length,2);});
