const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {chromium}=require(process.env.NOTEWORK_PLAYWRIGHT_PATH||'playwright');
const {attachKnowledgeBridge}=require('./ui-qa.cjs');
const project=path.resolve(__dirname,'..'),output=process.env.NOTEWORK_QA_OUTPUT||path.join(project,'qa-output','mobile');fs.mkdirSync(output,{recursive:true});
const tracked=['src/ui.mjs','styles.css','src/workspace-host.mjs','src/knowledge-space.mjs','src/note-preview.mjs','src/controller.mjs','src/conversation-flow.mjs','src/conversation-archive.mjs','src/knowledge-engine.mjs','src/portable-crypto.mjs'];
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),modules=()=>Object.fromEntries(tracked.map(file=>[file,hash(path.join(project,file))]));
const report={startedAt:new Date().toISOString(),syntheticContentOnly:true,productionModules:modules(),checks:[],screenshots:{},screenshotDimensions:{},pageErrors:[],externalRequests:[],downloads:[],popups:[],limitations:['Production mobile UI/controller with synthetic notes, model catalogs, credentials, and provider responses.','Actual KnowledgeEngine builds a desktop index, imports it with local source validation on a separate synthetic phone vault, and retrieves by keyword. No real service or vault content is used.','Touch gestures use Chromium CDP Input.dispatchTouchEvent, including multi-touch, rather than DOM-dispatched pointer events.','Viewport and keyboard-height behavior are browser/mobile-host emulation. A physical iOS or Android Obsidian installation has not been tested.']};
const check=(name,value,details)=>{report.checks.push({name,passed:!!value,...(details===undefined?{}:{details})});if(!value)throw Error(name+': '+JSON.stringify(details));};
const btn=(page,name)=>page.getByRole('button',{name,exact:true}),nav=(page,name)=>page.locator('.nw-tabs').getByRole('button',{name,exact:true}),settled=page=>page.waitForFunction(()=>window.fixtureReady&&!window.fixture.controller.state.busy);
const camera=async page=>{await page.waitForFunction(()=>document.querySelector('.nw-space-canvas')?.dataset.camera);return page.locator('.nw-space-canvas').evaluate(canvas=>JSON.parse(canvas.dataset.camera));};
async function capture(page,name){const file=path.join(output,name+'.png');await page.screenshot({path:file,fullPage:false});const png=fs.readFileSync(file);report.screenshots[name+'.png']=hash(file);report.screenshotDimensions[name+'.png']={width:png.readUInt32BE(16),height:png.readUInt32BE(20)};}
async function mount(page,surface){await page.evaluate(surface=>{const f=window.fixture;f.ui.destroy();const app=document.getElementById('app');app.style.height='calc(100dvh - 35px)';f.ui=f.mount(surface);},surface);}
async function dispatch(session,type,points){await session.send('Input.dispatchTouchEvent',{type,touchPoints:points.map((p,index)=>({x:p.x,y:p.y,id:p.id??index,radiusX:2,radiusY:2,force:1}))});}
async function tap(session,x,y,{wiggle=0}={}){await dispatch(session,'touchStart',[{x,y}]);if(wiggle)await dispatch(session,'touchMove',[{x:x+wiggle,y}]);await dispatch(session,'touchEnd',[]);}
async function swipe(session,start,end,steps=6){await dispatch(session,'touchStart',[start]);for(let at=1;at<=steps;at++){await dispatch(session,'touchMove',[{x:start.x+(end.x-start.x)*at/steps,y:start.y+(end.y-start.y)*at/steps}]);await new Promise(resolve=>setTimeout(resolve,20));}await dispatch(session,'touchEnd',[]);}
async function noOverflow(page,label){const result=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,root:document.querySelector('.notework-root').scrollWidth,client:document.querySelector('.notework-root').clientWidth,height:innerHeight,rootBottom:document.querySelector('.notework-root').getBoundingClientRect().bottom,windowScroll:scrollY}));check('Phone layout fits '+label,result.document<=result.width+1&&result.root<=result.client+1&&result.rootBottom<=result.height+1&&result.windowScroll===0,result);}
async function setup(page,origin){
  page.on('pageerror',error=>report.pageErrors.push(String(error)));page.on('request',request=>{if(/^https?:/i.test(request.url())&&!request.url().startsWith(origin+'/'))report.externalRequests.push(request.url());});page.on('download',download=>report.downloads.push(download.suggestedFilename()));page.on('popup',popup=>report.popups.push(popup.url()));
  await attachKnowledgeBridge(page);await page.goto(origin+'/tests/ui-fixture.html?surface=settings&mobile=1');await page.waitForFunction(()=>window.fixtureReady);await nav(page,'Connections').tap();
  check('Phone Connections exposes personal API keys and Jev but no desktop CLI or PC routes',await btn(page,'Use OpenAI API').count()===1&&await btn(page,'Use Claude API').count()===1&&await page.getByText('Connect Jev',{exact:true}).count()===1&&await page.locator('.nw-subscriptions').innerText().then(text=>text.trim()==='')&&await btn(page,'Continue with ChatGPT').count()===0&&await btn(page,'Continue with Claude Code').count()===0&&await btn(page,'Check this computer').count()===0&&await btn(page,'Load Ollama models').count()===0);
  await page.locator('[data-focus-id=key-openai]').fill('qa-only-synthetic-mobile-key');await btn(page,'Save key').click();await settled(page);await btn(page,'Load models').click();await settled(page);await btn(page,'Short connection test').click();await settled(page);
  check('Mobile API discovery and verification use the actual controller',await page.evaluate(()=>{const c=window.fixture.controller;return c.state.mode==='openai'&&c.state.verified&&c.state.model==='api-fixture-openai-unique';}));
  await nav(page,'Build').click();check('Phone Build requires computer sync and has no new embedding or semantic build',await page.getByText('Mobile requires a knowledge index built in Obsidian on your computer, synced together with its original notes.',{exact:true}).count()===1&&await btn(page,'Build knowledge').count()===0&&await page.locator('[data-focus-id=knowledge-embedding-route],[data-focus-id=knowledge-semantic-route]').count()===0);
  await mount(page,'workspace');await nav(page,'Graph').click();check('Unverified phone graph shows no note titles and directs to local sync verification',await page.locator('.nw-map-node').count()===0&&await btn(page,'Open sync settings').count()===1);await btn(page,'Open sync settings').click();check('Graph sync action opens the correct settings section',await page.evaluate(()=>window.fixture.trace.opened.at(-1)?.view==='build'));
  await page.evaluate(async()=>{
    const f=window.fixture;for(const group of ['Concepts','Methods','Records']){const folder='Research/Phone/'+group;f.folders.push({path:folder,name:group,children:[]});for(let at=0;at<10;at++){const prefix=group==='Concepts'?'ontology':group==='Methods'?'graph':'record';const titles=group==='Concepts'?['Source evidence','Knowledge layers','Concept identity','Typed properties','Topic boundaries']:group==='Methods'?['Scope filters','Graph traversal','Source validation','Hybrid retrieval','Chunk boundaries']:['Research journal','Review checkpoint','Study plan','Decision trail','Next question'];const title=prefix+' '+titles[at%5]+' '+(at+1),notePath=folder+'/'+title+'.md';const content='# '+title+'\n\nOntology and graph research use inspectable source evidence. These are invented examples.\n\n'+(at===0?Array.from({length:220},(_,line)=>'Source line '+(line+1)+': preserve the original note and verify its evidence before answering.').join('\n'):'Related concepts support a clear answer with source notes.')+'\n\nFINAL_COMPLETE_PHONE_NOTE\n<script>window.__phonePreviewExecuted=true</script>';f.notes.push({path:notePath,content});f.files.push({path:notePath,name:title+'.md',stat:{size:new TextEncoder().encode(content).byteLength,mtime:1,ctime:1}});f.tags.set(notePath,['#phone/'+group.toLowerCase()]);}}
    f.controller.setScope({mode:'folders',include:['Research/Phone'],exclude:[],tags:[],excludeTags:[]});
    const result=await window.__noteworkQaBridge({method:'build',input:{files:f.controller.scopeFiles(),scope:f.controller.effectiveScope(),embeddingRoute:'ollama',embeddingModel:'synthetic-embedding:local',semanticRoute:'llm',semanticModel:f.controller.state.model,maxNotes:60,maxCalls:200,consent:true},payload:{notes:f.notes,files:f.files,folders:f.folders,tags:[...f.tags]},mode:'openai',model:f.controller.state.model});if(result.error)throw Error(result.error);f.control.desktopIndex=result.value;f.control.syncedIndex=result.value;await f.controller.initializeRuntime();
  });
  check('Synced desktop index remains pending until local phone verification',await page.evaluate(()=>{const k=window.fixture.controller.state.knowledge;return k.phase==='import-required'&&k.index===null&&k.pendingImport.nodes.length===30;}));
  const before=await page.evaluate(()=>window.fixture.trace.calls.length);await mount(page,'settings');await nav(page,'Build').click();await btn(page,'Use synced knowledge on this device').click();await settled(page);
  check('Explicit synced import validates original notes locally without provider calls',await page.evaluate(count=>{const f=window.fixture,k=f.controller.state.knowledge;return k.phase==='ready'&&k.index?.portableImport?.verifiedNotes===30&&!k.pendingImport&&f.trace.calls.length===count&&f.trace.knowledge.some(item=>item.method==='mobile-import');},before));
  check('Phone import preserves the desktop index route with a verified local lineage',await page.evaluate(()=>{const i=window.fixture.controller.state.knowledge.index;return i.embedding.route==='ollama'&&i.portableImport.sourceVaultId!==i.vaultId&&i.chunks.length>30;}));await mount(page,'workspace');
}
async function touchRegression(page,session){
  await nav(page,'Graph').tap();await page.waitForFunction(()=>Number(document.querySelector('.nw-space-canvas')?.dataset.stars)===30);const bounds=await page.locator('.nw-space-canvas').boundingBox(),start={x:bounds.x+bounds.width*.45,y:bounds.y+bounds.height*.5};const base=await camera(page);await swipe(session,start,{x:start.x+45,y:start.y+28});const orbited=await camera(page);check('Real one-finger orbit changes 3D yaw and pitch without selecting a star',orbited.yaw!==base.yaw&&orbited.pitch!==base.pitch&&await page.evaluate(()=>window.fixture.controller.state.knowledge.selectedNodeIds.length===0));
  const mid={x:bounds.x+bounds.width*.5,y:bounds.y+bounds.height*.45};await dispatch(session,'touchStart',[{x:mid.x-30,y:mid.y,id:11},{x:mid.x+30,y:mid.y,id:12}]);await dispatch(session,'touchMove',[{x:mid.x-45+10,y:mid.y+12,id:11},{x:mid.x+45+10,y:mid.y+12,id:12}]);await dispatch(session,'touchEnd',[]);const pinched=await camera(page);check('Real two-finger gesture pinches zoom and pans the camera',pinched.zoom>orbited.zoom&&pinched.panX!==orbited.panX&&pinched.panY!==orbited.panY,{before:orbited,after:pinched});check('Multi-touch never accidentally selects a note',await page.evaluate(()=>window.fixture.controller.state.knowledge.selectedNodeIds.length===0));
  await btn(page,'Reset camera').tap();await btn(page,'Concepts (10)').tap();await page.waitForFunction(()=>Number(document.querySelector('.nw-space-canvas')?.dataset.stars)===10);check('Phone category control focuses its actual semantic region and future chat subset',await page.evaluate(()=>window.fixture.controller.state.knowledge.selectedCategory!=='all')&&await page.locator('.nw-space-canvas').evaluate(canvas=>JSON.parse(canvas.dataset.regions).length===1));
  const id=await page.getByRole('button',{name:'Select note ontology Source evidence 1',exact:true}).getAttribute('data-node-id');const point=await page.locator('.nw-space-canvas').evaluate((canvas,id)=>{const stars=JSON.parse(canvas.dataset.projection),p=stars.find(p=>p.id===id);const offsets=Array.from({length:16},(_,at)=>({x:12*Math.cos(at*Math.PI/8),y:12*Math.sin(at*Math.PI/8)}));const offset=offsets.sort((a,b)=>Math.min(...stars.filter(s=>s.id!==id).map(s=>Math.hypot(s.x-p.x-a.x,s.y-p.y-a.y)))-Math.min(...stars.filter(s=>s.id!==id).map(s=>Math.hypot(s.x-p.x-b.x,s.y-p.y-b.y)))).at(-1);return{x:p.x+offset.x,y:p.y+offset.y};},id),box=await page.locator('.nw-space-canvas').boundingBox();await tap(session,box.x+point.x,box.y+point.y,{wiggle:2});await page.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');check('Phone tap distinguishes small finger motion and retains a generous star pick target',await page.evaluate(id=>window.fixture.controller.state.knowledge.selectedNodeIds[0]===id,id),await page.evaluate(()=>window.fixture.controller.state.knowledge.selectedNodeIds));
  check('Phone star opens the complete safe-text source in a viewport-sized drawer',await page.locator('.nw-note-preview-content').evaluate(el=>el.textContent.includes('FINAL_COMPLETE_PHONE_NOTE')&&el.textContent.includes('<script>')&&el.scrollHeight>el.clientHeight)&&!(await page.evaluate(()=>window.__phonePreviewExecuted))&&await page.locator('.nw-note-preview').evaluate(el=>{const b=el.getBoundingClientRect();return b.x>=0&&b.y>=0&&b.right<=innerWidth&&b.bottom<=innerHeight;}));
  const body=await page.locator('.nw-note-preview-content').boundingBox(),windowBefore=await page.evaluate(()=>scrollY);await swipe(session,{x:body.x+body.width*.4,y:body.y+body.height*.75},{x:body.x+body.width*.4,y:body.y+body.height*.2},9);await page.waitForTimeout(180);const scroll=await page.locator('.nw-note-preview-content').evaluate(el=>el.scrollTop);check('Real touch scrolling stays inside full note preview',scroll>50&&await page.evaluate(()=>scrollY)===windowBefore,{previewScroll:scroll});
  const savedCamera=await camera(page),reads=await page.evaluate(()=>window.fixture.trace.previewReads.length);await page.waitForTimeout(450);await nav(page,'Chat').tap();await page.waitForFunction(()=>document.querySelector('.notework-root').dataset.view==='chat');await page.locator('[data-focus-id=question]').fill('UNSENT_PHONE_DRAFT');for(const label of ['History','Conversation map','Graph'])await nav(page,label).tap();await page.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');check('Phone view switches retain camera selected knowledge and full preview scroll',JSON.stringify(await camera(page))===JSON.stringify(savedCamera)&&await page.locator('.nw-note-preview-content').evaluate(el=>el.scrollTop>50)&&await page.evaluate(()=>window.fixture.trace.previewReads.length)===reads);
  await nav(page,'Chat').tap();check('Draft survives Graph History and Flow navigation',await page.locator('[data-focus-id=question]').inputValue()==='UNSENT_PHONE_DRAFT');check('Chat truthfully labels keyword retrieval of synced knowledge',(await page.locator('.nw-retrieval-note').innerText()).includes('Keyword retrieval on this device'));
  await page.locator('[data-focus-id=question]').fill('How does this selected ontology note support source evidence?');await btn(page,'Send question').tap();await settled(page);check('Phone answer uses the selected verified star through explicit keyword retrieval',await page.evaluate(id=>{const c=window.fixture.controller;return c.state.sources.length>0&&c.state.sources.every(source=>source.path===c.state.knowledge.index.nodes.find(node=>node.id===id).path)&&c.state.retrievalProof.strategy==='lexical'&&c.state.retrievalProof.indexRoute==='ollama';},id));
  await page.locator('[data-focus-id=question]').fill('ANOTHER_PHONE_DRAFT');await btn(page,'Save conversation').tap();await settled(page);await nav(page,'History').tap();check('Phone archive remains a real local conversation with original messages',await page.locator('.nw-history-item').count()===1);await nav(page,'Chat').tap();check('Conversation and next draft survive phone navigation',await page.locator('[data-focus-id=question]').inputValue()==='ANOTHER_PHONE_DRAFT'&&await page.locator('[aria-label="AI answer"]').count()===1);
}
async function viewportRegression(page,session){
  for(const viewport of [{width:320,height:700},{width:390,height:844},{width:430,height:932},{width:844,height:390}]){
    await page.setViewportSize(viewport);await nav(page,'Chat').tap();await page.waitForTimeout(60);await noOverflow(page,viewport.width+'x'+viewport.height+' Chat');check('Phone composer stays visible at '+viewport.width+'x'+viewport.height,await btn(page,'Send question').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight)&&await page.locator('[data-focus-id=question]').evaluate(el=>el.getBoundingClientRect().height>=44));check('Phone navigation and essential chat controls have 44px touch targets '+viewport.width,await page.locator('.nw-tabs button,.nw-chat-model select,.nw-actions>button').evaluateAll(nodes=>nodes.every(el=>el.getBoundingClientRect().height>=44)));
    await capture(page,'mobile-chat-'+viewport.width+'x'+viewport.height);await nav(page,'Graph').tap();await page.waitForTimeout(60);await noOverflow(page,viewport.width+'x'+viewport.height+' Graph');check('Phone graph is one readable pane without desktop split '+viewport.width,await page.locator('.nw-workspace-divider,.nw-workspace-conversation').count()===0&&await page.locator('.nw-space-canvas').evaluate(el=>el.clientHeight>=100));check('Phone preview remains inside viewport after orientation '+viewport.width,await page.locator('.nw-note-preview').evaluate(el=>{const b=el.getBoundingClientRect();return b.right<=innerWidth&&b.bottom<=innerHeight&&b.top>=0;})&&await page.locator('.nw-note-preview-content').evaluate(el=>el.clientHeight>=90));await capture(page,'mobile-preview-'+viewport.width+'x'+viewport.height);
    await btn(page,'Close note preview').tap();check('Close preview keeps chat selection and 44px camera controls '+viewport.width,await page.evaluate(()=>window.fixture.controller.state.knowledge.selectedNodeIds.length===1)&&await page.locator('.nw-map-controls>button').evaluateAll(nodes=>nodes.every(el=>el.getBoundingClientRect().height>=44)));await capture(page,'mobile-space-'+viewport.width+'x'+viewport.height);const hit=await page.locator('.nw-space-canvas').evaluate(canvas=>{const b=canvas.getBoundingClientRect(),stars=JSON.parse(canvas.dataset.projection);return{bounds:b.toJSON(),logicalHeight:canvas.height/devicePixelRatio,star:stars.find(s=>s.x>24&&s.x<b.width-24&&s.y>24&&s.y<b.height-24)};});check('Phone perspective uses actual short canvas coordinates '+viewport.width,Math.abs(hit.logicalHeight-hit.bounds.height)<=3,hit);if(hit.star){await tap(session,hit.bounds.x+hit.star.x,hit.bounds.y+hit.star.y);await page.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');check('Actual star tap matches projection after phone orientation '+viewport.width,await page.evaluate(id=>window.fixture.controller.state.knowledge.selectedNodeIds[0]===id,hit.star.id));await btn(page,'Close note preview').tap();}
    // Reopen through the actual keyboard-accessible star; selection remains unchanged.
    await page.getByRole('button',{name:'Select note ontology Source evidence 1',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');
  }
  await page.setViewportSize({width:390,height:844});await nav(page,'Chat').tap();await page.locator('[data-focus-id=question]').focus();await page.setViewportSize({width:390,height:460});await page.waitForTimeout(100);check('Keyboard-height viewport keeps draft and send composer accessible',await btn(page,'Send question').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight)&&await page.locator('[data-focus-id=question]').inputValue()==='ANOTHER_PHONE_DRAFT'&&await page.locator('.nw-chat-feed').evaluate(el=>el.clientHeight>=45));await capture(page,'mobile-keyboard-viewport');
  check('Phone capabilities never query PC hardware or run local model discovery',await page.evaluate(()=>!window.fixture.trace.hardwareChecks&&!window.fixture.trace.calls.some(call=>['ollama','embedding','chatgpt','codex','claude-code'].includes(call.mode))));
}
async function scopeRecovery(page){await page.setViewportSize({width:390,height:844});const before=await page.evaluate(()=>window.fixture.trace.calls.length);await page.evaluate(()=>window.fixture.controller.setScope({mode:'folders',include:['Research/Phone'],exclude:['Research/Phone/Concepts'],tags:[],excludeTags:[]}));await nav(page,'Graph').tap();check('Narrowing phone scope invalidates graph before local revalidation',await page.locator('.nw-map-node').count()===0&&await btn(page,'Open sync settings').count()===1);for(const view of ['History','Conversation map']){await nav(page,view).tap();check('Unverified '+view+' stays behind phone sync prerequisite',await btn(page,'Open sync settings').count()===1&&await page.locator('.nw-history-item,.nw-flow-observation').count()===0);}await mount(page,'settings');await nav(page,'Build').tap();await btn(page,'Use synced knowledge on this device').tap();await settled(page);check('Local revalidation prunes excluded phone notes',await page.evaluate(()=>window.fixture.controller.state.knowledge.index.nodes.length===20));await page.evaluate(()=>window.fixture.controller.setScope({mode:'folders',include:['Research/Phone'],exclude:[],tags:[],excludeTags:[]}));await btn(page,'Use synced knowledge on this device').tap();await settled(page);check('Broader phone scope recovers originals from the authoritative PC index',await page.evaluate(()=>window.fixture.controller.state.knowledge.index.nodes.length===30&&window.fixture.controller.state.knowledge.syncedSource.nodes.length===30));check('Scope recovery makes no API Jev or embedding requests',await page.evaluate(()=>window.fixture.trace.calls.length)===before);await mount(page,'workspace');}
async function run(page,origin,session){await setup(page,origin);await touchRegression(page,session);await viewportRegression(page,session);await scopeRecovery(page);check('English mobile UI excludes donation links credentials and executable note HTML',await page.locator('.nw-support,a[href*=buymeacoffee]').count()===0&&!(await page.locator('body').innerText()).includes('qa-only-synthetic-mobile-key')&&!(await page.locator('.notework-root').innerText()).match(/[\uac00-\ud7a3]/u));}
(async()=>{let server,browser,currentPage;try{const allowed=new Set(['tests/ui-fixture.html','styles.css']);function scan(directory){for(const item of fs.readdirSync(path.join(project,directory),{withFileTypes:true})){const rel=directory+'/'+item.name;if(item.isDirectory())scan(rel);else if(item.name.endsWith('.mjs'))allowed.add(rel);}}scan('src');server=http.createServer((request,response)=>{const target=new URL(request.url,'http://127.0.0.1').pathname.slice(1);if(!allowed.has(target)){response.writeHead(404);response.end();return;}response.setHeader('Cache-Control','no-store');response.setHeader('Content-Type',target.endsWith('.html')?'text/html; charset=utf-8':target.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');response.end(fs.readFileSync(path.join(project,target)));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-gpu']});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();currentPage=page;const session=await context.newCDPSession(page);await run(page,origin,session);
  const listing=await browser.newContext({viewport:{width:450,height:800},hasTouch:true,isMobile:true,deviceScaleFactor:2}),gallery=await listing.newPage();await setup(gallery,origin);await gallery.locator('[data-focus-id=question]').fill('How do my research notes connect source evidence and knowledge layers?');await btn(gallery,'Send question').tap();await settled(gallery);await capture(gallery,'notework-mobile-chat');await nav(gallery,'Graph').tap();await capture(gallery,'notework-mobile-space');await btn(gallery,'Concepts (10)').tap();await gallery.waitForTimeout(80);const galleryStar=await gallery.locator('.nw-space-canvas').evaluate(canvas=>{const target=window.fixture.controller.state.knowledge.index.nodes.find(node=>node.title==='ontology Source evidence 1');const star=JSON.parse(canvas.dataset.projection).find(star=>star.id===target.id),rect=canvas.getBoundingClientRect();return{x:rect.x+star.x,y:rect.y+star.y};});const galleryTouch=await listing.newCDPSession(gallery);await tap(galleryTouch,galleryStar.x,galleryStar.y);await gallery.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');report.previewLayout=await gallery.evaluate(()=>Object.fromEntries(['.notework-root','.nw-tabs','.nw-content','.nw-workspace-graph','.nw-map-viewport','.nw-note-preview'].map(selector=>{const el=document.querySelector(selector);return[selector,{rect:el.getBoundingClientRect().toJSON(),scroll:el.scrollTop,position:getComputedStyle(el).position,overflow:getComputedStyle(el).overflow}];})));await noOverflow(gallery,'900x1600 full note preview');await capture(gallery,'notework-mobile-preview');check('Community phone screenshots are 900x1600 synthetic captures',['notework-mobile-chat.png','notework-mobile-space.png','notework-mobile-preview.png'].every(name=>report.screenshotDimensions[name].width===900&&report.screenshotDimensions[name].height===1600));check('Phone runs without browser errors external requests downloads or popups',report.pageErrors.length===0&&report.externalRequests.length===0&&report.downloads.length===0&&report.popups.length===0,{pageErrors:report.pageErrors,externalRequests:report.externalRequests});report.passed=true;
}catch(error){if(currentPage&&!currentPage.isClosed()){await currentPage.screenshot({path:path.join(output,'mobile-failure.png')});report.failureLayout=await currentPage.evaluate(()=>({view:document.querySelector('.notework-root')?.dataset.view,nav:[...document.querySelectorAll('.nw-tabs button')].map(el=>({text:el.textContent,rect:el.getBoundingClientRect().toJSON()})),preview:document.querySelector('.nw-note-preview')?.getBoundingClientRect().toJSON()}));}report.passed=false;report.failure=String(error);process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));report.productionModulesAtEnd=modules();report.sourceChangedDuringRun=JSON.stringify(report.productionModules)!==JSON.stringify(report.productionModulesAtEnd);if(report.sourceChangedDuringRun)report.passed=false;report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(output,'mobile-ui-report.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify({passed:report.passed,checks:report.checks.length,failure:report.failure,screenshots:Object.keys(report.screenshots).length,sourceChangedDuringRun:report.sourceChangedDuringRun,report:path.join(output,'mobile-ui-report.json')},null,2));}})();
