import test from 'node:test';
import assert from 'node:assert/strict';
import {readScopedNotePreview,MAX_NOTE_PREVIEW_BYTES} from '../src/note-preview.mjs';

function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
function fixture(content='# Source note\r\n\r\nFull Markdown 🧠 한국어\n```js\nconst value = 1;\n```\nLast line.'){const path='Research/source.md';const file={path,basename:'Source note',stat:{mtime:10,size:new TextEncoder().encode(content).byteLength}};let current=file;let included=true;let archived=false;const reads=[];let scopeCalls=0;const vault={getAbstractFileByPath:value=>value===path?current:null,read:async value=>{reads.push(value.path);return content;},cachedRead:async()=>{throw new Error('Do not prefer cachedRead over read');}};const scopeFiles=()=>{scopeCalls++;return included&&current?[current]:[];};return {file,vault,reads,path,read:options=>readScopedNotePreview({vault,scopeFiles,path,isArchiveFile:()=>archived,...options}),scopeCalls:()=>scopeCalls,replace:value=>current=value,exclude:()=>included=false,archive:()=>archived=true};}

test('preview returns the exact full original Markdown including its final line and all Unicode',async()=>{const original='# Source\r\n\n'+('Full original line 🧠 한국어\n'.repeat(5000))+'LAST_ORIGINAL_LINE';const f=fixture(original);const result=await f.read();assert.deepEqual(result,{path:f.path,title:'Source note',content:original,mtime:10});assert.equal(result.content.length,original.length);assert.ok(result.content.endsWith('LAST_ORIGINAL_LINE'));assert.deepEqual(f.reads,[f.path]);assert.equal(f.scopeCalls(),2);});
test('preview supports local cachedRead only when the host has no read method',async()=>{const f=fixture();delete f.vault.read;f.vault.cachedRead=async file=>'Full fallback '+file.path;const result=await f.read();assert.equal(result.content,'Full fallback '+f.path);});
test('invalid or hidden host paths and non-Markdown files fail before any local read',async()=>{for(const path of ['../secret.md','C:/secret.md','/Research/source.md','.obsidian/secret.md','Research/../source.md','Research/source.txt','Research/source.md\0','Research\\source.md','Research/source.md#heading']){const f=fixture();await assert.rejects(f.read({path}),{code:'PREVIEW_INVALID_PATH'});assert.equal(f.reads.length,0);}});
test('deleted files and folders cannot be treated as source note previews',async()=>{const deleted=fixture();deleted.replace(null);await assert.rejects(deleted.read(),{code:'PREVIEW_NOT_FOUND'});assert.equal(deleted.reads.length,0);const folder=fixture();folder.replace({...folder.file,children:[]});await assert.rejects(folder.read(),{code:'PREVIEW_NOT_FOUND'});assert.equal(folder.reads.length,0);});
test('out-of-scope and archived notes are rejected before reading',async()=>{const f=fixture();f.exclude();await assert.rejects(f.read(),{code:'PREVIEW_OUTSIDE_SCOPE'});assert.equal(f.reads.length,0);const archived=fixture();archived.archive();await assert.rejects(archived.read(),{code:'PREVIEW_OUTSIDE_SCOPE'});assert.equal(archived.reads.length,0);});
test('scope and archive membership are checked again after an asynchronous read',async()=>{for(const change of ['exclude','archive']){const f=fixture();const pending=deferred();f.vault.read=()=>pending.promise;const action=f.read();f[change]();pending.resolve('OLD_SCOPE_CONTENT');await assert.rejects(action,{code:'PREVIEW_OUTSIDE_SCOPE'});}});
test('a file deleted or moved while reading never returns stale content',async()=>{for(const change of ['delete','move']){const f=fixture();const pending=deferred();f.vault.read=()=>pending.promise;const action=f.read();if(change==='delete')f.replace(null);else f.file.path='Private/moved.md';pending.resolve('STALE_NOTE_CONTENT');await assert.rejects(action,{code:'PREVIEW_CHANGED'});}});
test('modifications and same-path object replacement during read require a fresh preview',async()=>{for(const change of ['mtime','size','replace']){const f=fixture();const pending=deferred();f.vault.read=()=>pending.promise;const action=f.read();if(change==='replace')f.replace({...f.file,stat:{...f.file.stat}});else f.file.stat[change]++;pending.resolve('STALE_NOTE_CONTENT');await assert.rejects(action,{code:'PREVIEW_CHANGED'});}});
test('oversized notes have an explicit open-source fallback instead of silently truncated content',async()=>{const f=fixture();f.file.stat.size=MAX_NOTE_PREVIEW_BYTES+1;await assert.rejects(f.read(),error=>error.code==='PREVIEW_TOO_LARGE'&&error.message.includes('read it in full'));assert.equal(f.reads.length,0);const unicode=fixture();unicode.vault.read=async()=> '한'.repeat(Math.ceil(MAX_NOTE_PREVIEW_BYTES/3)+1);await assert.rejects(unicode.read(),{code:'PREVIEW_TOO_LARGE'});});
test('cancellation before or after a late read produces no preview result',async()=>{const early=fixture();const aborted=new AbortController();aborted.abort();await assert.rejects(early.read({signal:aborted.signal}),{name:'AbortError'});assert.equal(early.reads.length,0);const late=fixture();const signal=new AbortController();const pending=deferred();late.vault.read=()=>pending.promise;const action=late.read({signal:signal.signal});signal.abort();pending.resolve('Late text');await assert.rejects(action,{name:'AbortError'});});
test('reader and scope failures never expose raw errors or source content',async()=>{const f=fixture();f.vault.read=async()=>{throw new Error('PRIVATE_RAW_NOTE_OR_HOST_ERROR');};await assert.rejects(f.read(),error=>error.code==='PREVIEW_READ_FAILED'&&!error.message.includes('PRIVATE_RAW'));await assert.rejects(f.read({scopeFiles:()=>{throw new Error('PRIVATE_SCOPE_ERROR');}}),error=>error.code==='PREVIEW_SCOPE_UNAVAILABLE'&&!error.message.includes('PRIVATE_SCOPE'));await assert.rejects(f.read({scopeFiles:()=>Promise.resolve([f.file])}),{code:'PREVIEW_SCOPE_UNAVAILABLE'});});
test('missing host services and non-text reads produce a clear local preview error',async()=>{const f=fixture();await assert.rejects(f.read({vault:{}}),{code:'PREVIEW_UNAVAILABLE'});f.vault.read=async()=>({content:'not plain Markdown'});await assert.rejects(f.read(),{code:'PREVIEW_READ_FAILED'});});
