const fs=require('fs');
const path=require('path');
const http=require('http');
const crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.NOTEWORK_PLAYWRIGHT_PATH || 'playwright');
const root=path.resolve(__dirname,'..');
const out=process.env.NOTEWORK_QA_OUTPUT || path.join(root,'qa-output');
fs.mkdirSync(out,{recursive:true});
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sources=['src/ui.mjs','src/knowledge-space.mjs','src/controller.mjs','src/providers/claude-login-url.mjs','src/providers/codex-login-url.mjs','src/vault-search.mjs','src/archive-paths.mjs','src/runtime-storage.mjs','src/portable-crypto.mjs','src/knowledge-engine.mjs','src/conversation-archive.mjs','src/providers/ollama-embeddings.mjs','src/providers/jev.mjs','styles.css'];
const report={startedAt:new Date().toISOString(),productionModules:Object.fromEntries(sources.map(p=>[p,sha(path.join(root,p))])),fixtureSha256:sha(path.join(root,'tests/ui-fixture.html')),checks:[],screenshots:[],pageErrors:[],externalRequests:[],downloads:[],popups:[],serverRequests:[],languageSnapshots:0,languageViolations:[],limitations:['Unchanged production UI/controller/search modules served from a local allowlist.','All providers, secrets, accounts and vault notes are synthetic English fixtures.','No real authentication, provider requests, Obsidian APIs or native plugin installation.','The English-only UI assertion does not restrict the language of actual user notes or model responses.']};
function check(name,condition,details){report.checks.push({name,passed:!!condition,...(details===undefined?{}:{details})});if(!condition)throw Error(name+': '+JSON.stringify(details));}
async function languageSnapshot(page){const found=await page.evaluate(()=>{const root=document.querySelector('.notework-root');if(!root)return[];const chunks=[root.textContent,...Array.from(root.querySelectorAll('[aria-label],[title],[placeholder]'),x=>[x.getAttribute('aria-label'),x.getAttribute('title'),x.getAttribute('placeholder')].filter(Boolean).join(' '))];return chunks.filter(x=>/[\uAC00-\uD7A3]/u.test(x)).map(x=>x.slice(0,800));});report.languageSnapshots++;for(const text of found)if(!report.languageViolations.includes(text))report.languageViolations.push(text);}
async function shot(page,name){await languageSnapshot(page);const file=path.join(out,name+'.png');await page.screenshot({path:file,fullPage:true});report.screenshots.push(file);}
async function state(page){await languageSnapshot(page);return page.evaluate(()=>structuredClone(window.fixture.controller.state));}
async function settled(page){await page.waitForFunction(()=>window.fixtureReady&&!window.fixture.controller.state.busy);}
const nav=(page,text)=>page.locator('.nw-tabs').getByRole('button',{name:text,exact:true});
const btn=(page,text)=>page.getByRole('button',{name:text,exact:true});
async function chooseStar(page,name,options={}){const close=page.getByRole('button',{name:'Close note preview',exact:true});if(await close.count())await close.click();const id=await page.getByRole('button',{name:'Select note '+name,exact:true}).getAttribute('data-node-id');const point=await page.locator('.nw-space-canvas').evaluate((canvas,id)=>JSON.parse(canvas.dataset.projection).find(star=>star.id===id),id);await page.locator('.nw-space-canvas').click({position:{x:point.x,y:point.y},...options});}
const status=page=>page.locator('.nw-status');
async function details(page,text){const d=page.locator('details').filter({has:page.getByText(text,{exact:true})});if(!await d.evaluate(x=>x.open))await d.locator('summary').click();return d;}
async function consent(page,value){check('Chat uses the explicit Send action without a mandatory checkbox',await page.locator('.nw-chat-composer input[type=checkbox]').count()===0);}
async function question(page,text){await page.locator('[data-focus-id="question"]').fill(text);}
async function noOverflow(page,label){const v=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,body:document.body.scrollWidth}));check('No horizontal overflow '+label,v.document<=v.width+1&&v.body<=v.width+1,v);const clipped=await page.locator('.nw-content h1,.nw-content h2,.nw-content h3').evaluateAll(xs=>xs.filter(x=>x.scrollWidth>x.clientWidth+1).map(x=>x.textContent));check('No clipped headings '+label,clipped.length===0,clipped);}
async function scopeCheckbox(page,folder,value){await page.locator('.nw-folder-row').filter({has:page.locator('input[aria-label="Include folder '+folder+'"]')}).locator('input').setChecked(value);}
const scopeTab=(page,name)=>page.getByRole('tab',{name,exact:true});
const folderRow=(page,path)=>page.locator('.nw-folder-row').filter({has:page.locator('input[aria-label="Include folder '+path+'"]')});
const tagCheck=(page,tag)=>page.getByRole('checkbox',{name:'Include tag '+tag,exact:true});
async function attachKnowledgeBridge(page){
  const {KnowledgeEngine}=await import(pathToFileURL(path.join(root,'src/knowledge-engine.mjs')).href);const {ConversationArchive}=await import(pathToFileURL(path.join(root,'src/conversation-archive.mjs')).href);
  const records=new Map(),folderRecords=new Map(),tagRecords=new Map();let reads=[],archiveSequence=0;const archivePaths=new Set();
  const vault={getName:()=> 'Synthetic research vault',adapter:{getBasePath:()=> 'synthetic-only-vault',exists:async p=>records.has(p)||folderRecords.has(p)},getMarkdownFiles:()=>[...records.values()].map(r=>r.file),getAbstractFileByPath:p=>records.get(p)?.file||folderRecords.get(p)||null,read:async f=>{reads.push(f.path);if(!records.has(f.path))throw Error('Synthetic note missing');return records.get(f.path).content;},createFolder:async p=>folderRecords.set(p,{path:p,children:[]}),create:async(p,content)=>{if(records.has(p))throw Error('Synthetic path already exists');const file={path:p,name:p.split('/').pop(),stat:{size:Buffer.byteLength(content),mtime:1,ctime:1},noteworkArchive:true};records.set(p,{file,content});archivePaths.add(p);return file;},process:async(file,update)=>{const record=records.get(file.path);record.content=update(record.content);record.file.stat.size=Buffer.byteLength(record.content);return record.content;}};
  const embeddingProvider={prepareModel:async model=>({fingerprint:'synthetic-local-embedding-v1'}),embed:async(texts,{model})=>({dimension:3,fingerprint:'synthetic-local-embedding-v1',vectors:texts.map(text=>[1,/graph/i.test(text)?1:.2,/ontology/i.test(text)?1:.1])})};
  const engine=new KnowledgeEngine({vault,getTags:file=>tagRecords.get(file.path)||[],embeddingProvider});const mobileEngine=new KnowledgeEngine({vault:{...vault,adapter:{...vault.adapter,getBasePath:()=> 'synthetic-phone-vault'}},getTags:file=>tagRecords.get(file.path)||[],embeddingProvider});const archive=new ConversationArchive({vault,idFactory:()=> 'synthetic-conversation-'+(++archiveSequence),clock:()=>new Date('2026-10-06T09:00:00.000Z')});
  report.limitations.push('KnowledgeEngine and ConversationArchive run unchanged in Node via a Playwright binding, with a synthetic vault and synthetic embedding/analysis responses; this validates UI/controller integration rather than real Obsidian/cloud performance.');
  await page.exposeFunction('__noteworkQaBridge',async({method,input,payload,mode,model})=>{
    reads=[];for(const file of payload.files){const note=payload.notes.find(note=>note.path===file.path);if(note)records.set(file.path,{file,content:note.content});}for(const folder of payload.folders)folderRecords.set(folder.path,folder);for(const [p,tags]of payload.tags)tagRecords.set(p,tags);let value;const progress=[];
    try{
      if(method==='build'){
        let progressQueue=Promise.resolve();const llmCall=async prompt=>{report.syntheticAnalysisCalls=(report.syntheticAnalysisCalls||0)+1;await page.evaluate(({mode,model,prompt})=>window.fixture.trace.calls.push({mode,model,type:'analysis',input:prompt}),{mode,model,prompt});await new Promise(resolve=>setTimeout(resolve,55));const body=JSON.parse(prompt.slice(prompt.indexOf('\n')+1));if(prompt.startsWith('Create '))return JSON.stringify({categories:[{label:'Concepts',description:'Concept explanations'},{label:'Methods',description:'Research methods'},{label:'Records',description:'Other research records'}]});if(prompt.startsWith('Classify '))return JSON.stringify({notes:body.notes.map(note=>({id:note.id,category:body.categories.find(category=>category.label===(/graph/i.test(note.title)?'Methods':/ontology/i.test(note.title)?'Concepts':'Records'))?.id||'other',layer:/graph/i.test(note.title)?'reference':/ontology/i.test(note.title)?'knowledge':'action',hierarchyLevel:/graph/i.test(note.title)?'detail':/ontology/i.test(note.title)?'overview':'topic'}))});return JSON.stringify({pairs:body.pairs.map(pair=>({source:pair.source,target:pair.target,kind:'topic',relatedProbability:.8,score:.7}))});};
        value=await engine.build({...input,llmCall,onProgress:p=>{progress.push(p);progressQueue=progressQueue.then(()=>page.evaluate(p=>window.fixture.controller.knowledge({progress:p}),p));}});await progressQueue;
      }else if(method==='retrieve')value=await engine.retrieve(input);else if(method==='mobile-import')value=await mobileEngine.importPortableIndex({...input,onProgress:p=>progress.push(p)});else if(method==='mobile-retrieve')value=await mobileEngine.retrieve(input);else if(method==='archive-save')value=await archive.save(input);else if(method==='archive-list')value=await archive.list(input);else if(method==='archive-load')value=await archive.load(input);else throw Error('Unknown synthetic bridge method');
      return{value,progress,reads,archives:[...archivePaths].map(path=>({path,content:records.get(path).content}))};
    }catch(error){return{error:error.message,reads};}
  });
}
async function knowledgeHistoryUX(page){
  await page.evaluate(()=>{window.fixture.control.behavior='normal';window.fixture.controller.newConversation();window.fixture.controller.setScope({...window.fixture.controller.state.scope,exclude:[...window.fixture.controller.state.scope.exclude,'Research/huge.md']});});await nav(page,'Knowledge').click();
  const callsBefore=await page.evaluate(()=>window.fixture.trace.calls.length);check('Knowledge build starts with visible scope and explicit Build action',!await btn(page,'Build knowledge').isDisabled()&&(await page.locator('.nw-build-scope').innerText()).includes('All 3 notes in your saved scope')&&await page.getByRole('checkbox',{name:'Allow this knowledge build',exact:true}).count()===0);
  check('Opening Knowledge makes no provider calls',await page.evaluate(()=>window.fixture.trace.calls.length)===callsBefore);
  await page.locator('[data-focus-id="knowledge-embedding-route"]').selectOption('ollama');await btn(page,'Load embedding models').click();await settled(page);await page.locator('[data-focus-id="knowledge-embedding-model"]').selectOption('synthetic-embedding:local');
  check('Embedding model comes from installed catalog and selection is explicit',await page.locator('[data-focus-id="knowledge-embedding-model"]').inputValue()==='synthetic-embedding:local'&&await page.evaluate(()=>window.fixture.trace.calls.some(call=>call.mode==='embedding'&&call.type==='listModels')));
  await page.locator('[data-focus-id="knowledge-semantic-route"]').selectOption('llm');await page.getByRole('checkbox',{name:'Limit notes',exact:true}).check();await page.locator('[data-focus-id="knowledge-max-notes"]').fill('20');await page.getByRole('checkbox',{name:'Limit AI requests',exact:true}).check();await page.locator('[data-focus-id="knowledge-max-calls"]').fill('4');
  check('Build request budget and cloud consent are visible',!await btn(page,'Build knowledge').isDisabled()&&(await page.locator('.nw-build-scope').innerText()).includes('AI request limit: 4')&&await page.getByRole('checkbox',{name:'Allow this knowledge build',exact:true}).count()===0);
  await btn(page,'Build knowledge').click();await page.waitForFunction(()=>window.fixture.controller.state.knowledge.phase==='building'&&window.fixture.controller.state.knowledge.progress?.total>0);
  check('Knowledge progress displays real engine stage and counts',await page.locator('.nw-build-status progress').count()===1&&(await page.locator('.nw-build-status').innerText()).match(/taxonomy|reading|classifying|embedding|relations/));await settled(page);
  const built=await state(page);check('Real engine builds bounded local embeddings and AI taxonomy',built.knowledge.phase==='ready'&&built.knowledge.index.nodes.length===3&&built.knowledge.index.embedding.model==='synthetic-embedding:local'&&built.knowledge.index.semantic.taxonomySource==='llm'&&built.knowledge.index.stats.semanticCalls<=4,built.knowledge);
  check('No private sibling system or explicitly excluded note enters knowledge index',built.knowledge.index.nodes.every(node=>['Research/ontology.md','Research/Methods/graph.md','Research/unmatched.md'].includes(node.path))&&await page.evaluate(()=>window.fixture.trace.calls.filter(call=>call.type==='analysis').every(call=>!/EXCLUDED_PRIVATE_MARKER|SIBLING_BOUNDARY_MARKER|OUTSIDE_PRIVATE_MARKER|SYSTEM_MARKER|OVERSIZE_MARKER/.test(call.input))));
  check('Knowledge renders provenance and source-derived dynamic categories',(await page.locator('[aria-label="Knowledge provenance"]').innerText()).includes('synthetic-embedding:local')&&await page.getByRole('button',{name:'Concepts (1)',exact:true}).count()===1&&await page.locator('.nw-map-node').count()===3);
  const allView=await page.locator('.nw-space-canvas').getAttribute('data-projection');const analysisBefore=await page.evaluate(()=>window.fixture.trace.calls.filter(call=>call.type==='analysis').length);await page.getByRole('button',{name:'Concepts (1)',exact:true}).click();
  check('Category selection locally filters and reflows 3D stars without paid request',await page.locator('.nw-map-node').count()===1&&await page.getByRole('button',{name:'Select note ontology',exact:true}).count()===1&&await page.locator('.nw-space-canvas').getAttribute('data-projection')!==allView&&await page.evaluate(()=>window.fixture.trace.calls.filter(call=>call.type==='analysis').length)===analysisBefore);
  await btn(page,'Category regions').click();check('Canvas semantic regions use the model category label',await page.locator('.nw-space-canvas').evaluate(canvas=>JSON.parse(canvas.dataset.regions).join('|')==='Concepts'));await btn(page,'Layer regions').click();
  await page.getByRole('button',{name:'Select note ontology',exact:true}).focus();await page.keyboard.press('Enter');check('Keyboard node selection exposes exact source quote and hash',(await page.locator('[aria-label="Selected note evidence"]').innerText()).includes('ALLOWED_ONTOLOGY')&&(await page.locator('[aria-label="Selected note evidence"]').innerText()).includes('Content hash:')&&(await page.locator('[aria-label="Selected note evidence"]').innerText()).includes('model suggestions'));
  await btn(page,'Open source note').click();check('Knowledge opens actual selected source path',await page.evaluate(()=>window.fixture.trace.opened.at(-1)==='Research/ontology.md'));
  await page.getByRole('button',{name:'All notes (3)',exact:true}).click();await chooseStar(page,'ontology');await chooseStar(page,'graph',{modifiers:['Shift']});check('Shift selection stores both real node IDs',(await state(page)).knowledge.selectedNodeIds.length===2);
  const original=await page.locator('.nw-space-canvas').getAttribute('data-camera');await btn(page,'Zoom in').click();const zoomed=await page.locator('.nw-space-canvas').getAttribute('data-camera');check('3D zoom changes perspective camera',JSON.parse(zoomed).zoom>JSON.parse(original).zoom);await btn(page,'Reset camera').click();check('Reset camera restores perspective',await page.locator('.nw-space-canvas').getAttribute('data-camera')===original);
  const bounds=await page.locator('.nw-space-canvas').boundingBox();await page.mouse.move(bounds.x+5,bounds.y+5);await page.mouse.down();await page.mouse.move(bounds.x+45,bounds.y+35);await page.mouse.up();check('3D dragging changes orbit yaw and pitch',await page.locator('.nw-space-canvas').getAttribute('data-camera')!==original);await btn(page,'Reset camera').click();
  await shot(page,'knowledge-desktop');await page.setViewportSize({width:320,height:1000});await page.waitForFunction(()=>document.querySelector('.nw-space-canvas').getBoundingClientRect().width<310);check('Narrow pane retains selectable stars and real 3D projected coordinates',await page.locator('.nw-map-node').evaluateAll(nodes=>nodes.every(node=>Math.abs(node.getBoundingClientRect().width-20)<.1))&&await page.locator('.nw-space-canvas').evaluate(canvas=>JSON.parse(canvas.dataset.projection).every(star=>Number.isFinite(star.depth))));await page.setViewportSize({width:980,height:1000});await page.waitForFunction(()=>document.querySelector('.nw-space-canvas').getBoundingClientRect().width>500);await chooseStar(page,'ontology',{modifiers:['Shift']});await chooseStar(page,'graph',{modifiers:['Shift']});check('Unchecking the last explicit node means no notes rather than broadening retrieval',(await state(page)).knowledge.selectedNodesActive===true&&(await state(page)).knowledge.selectedNodeIds.length===0&&await btn(page,'Chat with this selection').isDisabled()&&(await page.locator('.nw-knowledge-selection').innerText()).includes('No notes selected'));
  await nav(page,'Chat').click();await consent(page,true);check('Empty explicit selection cannot send and consent describes relevant conversation turns',await btn(page,'Send question').isDisabled()&&(await page.locator('.nw-retrieval-note').innerText()).includes('No notes selected')&&await page.locator('.nw-chat-composer input[type=checkbox]').count()===0);
  await nav(page,'Knowledge').click();await btn(page,'Clear knowledge selection').click();check('Clearing selection explicitly restores all indexed notes',(await state(page)).knowledge.selectedNodesActive===false&&(await state(page)).knowledge.selectedCategory==='all');await chooseStar(page,'ontology');await btn(page,'Chat with this selection').click();check('Chat with selection navigates with the real retrieval boundary',(await state(page)).tab==='chat'&&(await state(page)).knowledge.selectedNodeIds.length===1&&(await page.locator('.nw-retrieval-note').innerText()).includes('1 selected notes'));
  await page.locator('[data-focus-id="chat-model"]').selectOption('tenant-model-zeta-2049');await page.locator('[data-focus-id="chat-model"]').selectOption('gpt-6.1-sol');check('Changing Chat model clears verification and consent',!(await state(page)).verified&&!(await state(page)).consent&&await btn(page,'Send question').isDisabled());await btn(page,'Test chat model').click();await settled(page);await question(page,'How does ontology organize knowledge?');await consent(page,true);await btn(page,'Send question').click();await settled(page);
  const answer=await state(page);check('Selected model receives only the selected indexed note',answer.sources.length===1&&answer.sources[0].path==='Research/ontology.md'&&answer.messages.at(-1).model==='gpt-6.1-sol'&&await page.evaluate(()=>{const input=window.fixture.trace.calls.filter(call=>call.type==='generate'&&!call.verify).at(-1).input;return input.includes('ALLOWED_ONTOLOGY')&&!input.includes('ALLOWED_GRAPH');}));
  await details(page,'Retrieval details');check('Retrieval proof presents chunk counts and selection without object coercion',(await page.locator('.nw-retrieval-proof').innerText()).includes('1 matched chunks')&&(await page.locator('.nw-retrieval-proof').innerText()).includes('Selected note filter: 1 notes')&&!(await page.locator('.nw-retrieval-proof').innerText()).includes('[object Object]'));await details(page,'Inspect retrieved excerpt');check('Retrieved excerpt includes original text and content hash',(await page.locator('.nw-source-excerpt').innerText()).includes('ALLOWED_ONTOLOGY')&&(await page.locator('.nw-source-excerpt').innerText()).includes('Hash:'));
  await btn(page,'Save conversation').click();await page.waitForFunction(()=>window.fixture.controller.state.history.length===1&&window.fixture.controller.state.archivePath);check('Save writes real archive Markdown without a key',await page.evaluate(()=>{const f=window.fixture;return f.notes.some(note=>note.path===f.controller.state.archivePath&&note.content.includes('notework-conversation-data:v1:')&&note.content.includes('ALLOWED\\_ONTOLOGY')&&!note.content.includes('qa-only-synthetic-key'));}));
  await nav(page,'History').click();await details(page,'Archive settings');check('History suggests actual visible vault folders while allowing new relative folders',await page.locator('[data-focus-id="archive-folder"]').getAttribute('list')==='notework-archive-folders'&&await page.locator('#notework-archive-folders option').evaluateAll(options=>options.some(option=>option.value==='Research/Methods')&&options.every(option=>!option.value.startsWith('.')))&&(await page.locator('.nw-archive-settings').innerText()).includes('Choose an existing folder'));check('History shows actual saved file and opt-in auto-save',(await page.locator('.nw-history-list').innerText()).includes('How does ontology organize knowledge?')&&!await page.getByRole('checkbox',{name:'Save after every answer',exact:true}).isChecked());await btn(page,'Open saved conversation').click();check('History opens saved Markdown source',await page.evaluate(()=>window.fixture.trace.opened.at(-1)===window.fixture.controller.state.archivePath));await shot(page,'history-desktop');
  await btn(page,'New chat').click();check('New chat clears active conversation without deleting archive',(await state(page)).messages.length===0&&(await state(page)).history.length===1);await page.locator('.nw-history-item>button').click();await settled(page);check('History reload restores model-tagged turns and source evidence',(await state(page)).tab==='chat'&&(await state(page)).messages.length===2&&(await state(page)).messages.at(-1).model==='gpt-6.1-sol'&&(await state(page)).sources[0].contentHash&&!(await state(page)).consent);
  await nav(page,'History').click();await details(page,'Archive settings');await page.locator('[data-focus-id="archive-folder"]').fill('../Private');await btn(page,'Apply archive settings').click();await page.waitForFunction(()=>window.fixture.controller.state.status.includes('inside the current vault'));check('Archive folder rejects traversal without changing accepted folder',await page.evaluate(()=>window.fixture.controller.settings.archive.folder==='Notework/Chats'));
  await page.locator('[data-focus-id="archive-folder"]').fill('Notework/Chats');await page.getByRole('checkbox',{name:'Save after every answer',exact:true}).check();await btn(page,'Apply archive settings').click();await page.waitForFunction(()=>window.fixture.controller.settings.archive.autoSave===true);await nav(page,'Chat').click();await question(page,'What evidence supports ontology?');await consent(page,true);await btn(page,'Send question').click();await settled(page);check('Opt-in auto-save updates same real conversation and excludes archive from retrieval',(await state(page)).history.length===1&&(await state(page)).history[0].messageCount===4&&await page.evaluate(()=>window.fixture.controller.scopeFiles().every(file=>!file.noteworkArchive)));
  await shot(page,'knowledge-chat-desktop');await page.setViewportSize({width:320,height:1000});for(const view of ['Knowledge','Chat','History']){await nav(page,view).click();await noOverflow(page,'320 integrated '+view);await shot(page,'knowledge-'+view.toLowerCase()+'-320-light');}
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.evaluate(()=>{for(const [key,value]of Object.entries({'--text-normal':'#e7eaf0','--text-muted':'#b7bdc9','--text-accent':'#86afff','--background-modifier-hover':'#303848','--background-primary':'#181c26','--background-secondary':'#232936','--background-modifier-border':'#3a4354'}))document.documentElement.style.setProperty(key,value);document.body.style.background='#181c26';});for(const view of ['Knowledge','Chat','History']){await nav(page,view).click();await noOverflow(page,'320 dark integrated '+view);await shot(page,'knowledge-'+view.toLowerCase()+'-320-dark');}
  await page.setViewportSize({width:1200,height:800});await nav(page,'Knowledge').click();await listingScreenshot(page,'listing-knowledge');await nav(page,'History').click();await listingScreenshot(page,'listing-history');
  await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});await page.evaluate(()=>{for(const key of ['--text-normal','--text-muted','--text-accent','--background-modifier-hover','--background-primary','--background-secondary','--background-modifier-border'])document.documentElement.style.removeProperty(key);document.body.style.removeProperty('background');});await page.setViewportSize({width:980,height:1000});
}
async function scopeUX(page){
  await nav(page,'Scope').click();
  check('Scope has separate Folders and Tags tabs',await scopeTab(page,'Folders').count()===1&&await scopeTab(page,'Tags').count()===1&&await scopeTab(page,'Folders').getAttribute('aria-selected')==='true');
  await btn(page,'Collapse all').click();check('Collapse all preserves top-level folders and hides descendants',await folderRow(page,'Research').isVisible()&&await folderRow(page,'Research/Methods').count()===0);
  await btn(page,'Expand Research').click();check('Expanding one parent reveals its immediate children',await folderRow(page,'Research/Methods').isVisible()&&await folderRow(page,'Research/Methods/Deep').count()===0);
  await btn(page,'Expand Research/Methods').click();await btn(page,'Expand Research/Methods/Deep').click();
  const depths=await page.locator('.nw-folder-row').evaluateAll(rows=>rows.filter(row=>['Research','Research/Methods','Research/Methods/Deep','Research/Methods/Deep/Examples'].includes(row.dataset.folder)).map(row=>({path:row.dataset.folder,padding:parseInt(row.style.paddingInlineStart),depth:Number(row.getAttribute('aria-level')),text:row.textContent})));
  check('Folder hierarchy has increasing indentation and explicit depth',depths.length===4&&depths.every(row=>row.text.includes('Depth '+row.depth))&&[1,2,3,4].every(depth=>depths.some(row=>row.depth===depth&&row.padding===8+(depth-1)*18)),depths);
  check('Real empty folders remain selectable',await folderRow(page,'Empty').isVisible()&&(await folderRow(page,'Empty').innerText()).includes('0 notes'));
  await page.locator('[data-focus-id="scope-all"]').uncheck();await scopeCheckbox(page,'Research',true);
  check('Selecting parent checks all visible descendants while preserving expanded folders',await page.locator('.nw-folder-row').evaluateAll(rows=>rows.filter(row=>row.dataset.folder==='Research'||row.dataset.folder.startsWith('Research/')).every(row=>row.querySelector('input').checked&&!row.querySelector('input').indeterminate))&&await folderRow(page,'Research/Methods/Deep/Examples').isVisible());
  await scopeCheckbox(page,'Research/Methods',false);check('Clearing child displays partial parent and excludes descendant branch',await folderRow(page,'Research').locator('input').evaluate(input=>input.indeterminate&&!input.checked)&&await page.evaluate(()=>window.fixture.ui.scopeDraft.exclude.includes('Research/Methods')));
  await scopeCheckbox(page,'Research',true);await btn(page,'Collapse Research').click();check('Collapsed selected parent reports full subtree inclusion and counts',(await folderRow(page,'Research').innerText()).includes('5 notes · 4 subfolders')&&await folderRow(page,'Research').locator('.nw-folder-inclusion').isVisible()&&await folderRow(page,'Research/Methods').count()===0);
  await page.locator('[data-focus-id="scope-filter"]').fill('Examples');check('Folder search retains ancestors and expands matching hierarchy',await folderRow(page,'Research').isVisible()&&await folderRow(page,'Research/Methods').isVisible()&&await folderRow(page,'Research/Methods/Deep').isVisible()&&await folderRow(page,'Research/Methods/Deep/Examples').isVisible()&&await folderRow(page,'Research-old').count()===0);
  await page.locator('[data-focus-id="scope-filter"]').fill('');await btn(page,'Expand all').click();await scopeCheckbox(page,'Research/private',false);
  await scopeTab(page,'Tags').click();check('Tags tab explains folder intersection and nested tags',(await page.locator('.nw-scope-panel').innerText()).includes('within your folder scope')&&(await page.locator('.nw-scope-panel').innerText()).includes('#topic/child'));
  check('Tag catalog counts parent matches once per note',(await page.locator('[data-tag="#knowledge"]').innerText()).includes('5 notes in vault'));
  await tagCheck(page,'#knowledge').check();check('Parent tag selection visibly includes nested tags',await tagCheck(page,'#knowledge/ontology').isChecked()&&await tagCheck(page,'#knowledge/graph').isChecked());
  await tagCheck(page,'#knowledge/graph').uncheck();check('Clearing inherited nested tag stores a working exclusion',await page.evaluate(()=>window.fixture.ui.scopeDraft.excludeTags.includes('#knowledge/graph'))&&await tagCheck(page,'#knowledge').evaluate(input=>input.indeterminate));
  await page.locator('[data-focus-id="tag-exclude"]').fill('#knowledge');check('Excluded parent disables nested tags with visible reason',await tagCheck(page,'#knowledge/graph').isDisabled()&&(await page.locator('[data-tag="#knowledge/graph"]').innerText()).includes('Excluded by #knowledge'));
  await page.locator('[data-focus-id="tag-exclude"]').fill('#knowledge/graph');
  await scopeTab(page,'Folders').click();check('Switching scope tabs retains both folder and tag drafts',await page.evaluate(()=>window.fixture.ui.scopeDraft.include.includes('Research')&&window.fixture.ui.scopeDraft.exclude.includes('Research/private')&&window.fixture.ui.scopeDraft.tags.includes('#knowledge')&&window.fixture.ui.scopeDraft.excludeTags.includes('#knowledge/graph')));
  check('Scope preview counts actual folder and tag intersection',(await page.locator('.nw-scope-summary').innerText()).includes('Selected scope: 1 notes'));
  await shot(page,'scope-folders-desktop');await noOverflow(page,'980 folder tree');await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 folder tree');await shot(page,'scope-folders-mobile');
  await scopeTab(page,'Tags').click();await noOverflow(page,'390 tags');await shot(page,'scope-tags-mobile');await page.setViewportSize({width:980,height:1000});await shot(page,'scope-tags-desktop');
  await scopeTab(page,'Folders').click();await scopeTab(page,'Folders').focus();await page.keyboard.press('ArrowRight');check('Scope tabs support keyboard navigation',await scopeTab(page,'Tags').getAttribute('aria-selected')==='true'&&await scopeTab(page,'Tags').evaluate(tab=>document.activeElement===tab));
  await btn(page,'Apply scope').click();await settled(page);check('Applied scope persists folder and tag conditions together',await page.evaluate(()=>{const scope=window.fixture.trace.savedSettings.at(-1).scope;return scope.mode==='folders'&&scope.include.includes('Research')&&scope.exclude.includes('Research/private')&&scope.tags.includes('#knowledge')&&scope.excludeTags.includes('#knowledge/graph');}));
  await question(page,'Ontology');await consent(page,true);await page.evaluate(()=>window.fixture.trace.reads=[]);await btn(page,'Send question').click();await settled(page);
  check('Folder and tag scope filters actual transmitted note context',await page.evaluate(()=>{const request=window.fixture.trace.calls.filter(call=>call.type==='generate'&&!call.verify).at(-1);return window.fixture.controller.state.sources.map(source=>source.path).join('|')==='Research/ontology.md'&&[...new Set(window.fixture.trace.reads)].join('|')==='Research/ontology.md'&&request.input.includes('ALLOWED_ONTOLOGY')&&!request.input.includes('ALLOWED_GRAPH')&&!request.input.includes('EXCLUDED_PRIVATE_MARKER');}));
  await nav(page,'Scope').click();await scopeTab(page,'Tags').click();await btn(page,'Clear selected tags').click();await page.locator('[data-focus-id="tag-exclude"]').fill('');await scopeTab(page,'Folders').click();await page.locator('[data-focus-id="scope-all"]').check();await btn(page,'Apply scope').click();await settled(page);await page.evaluate(()=>window.fixture.trace.reads=[]);
}
async function workbenchDesignUX(page){
  check('Workbench keeps one inline network mark and native font',await page.locator('.nw-network-mark').count()===1&&await page.locator('.nw-network-mark').getAttribute('aria-hidden')==='true'&&await page.locator('.notework-root').evaluate(element=>getComputedStyle(element).fontFamily===getComputedStyle(document.body).fontFamily));
  await nav(page,'Connections').focus();await page.keyboard.press('ArrowRight');
  check('Workbench navigation moves to Scope with ArrowRight',await nav(page,'Scope').getAttribute('aria-current')==='page'&&await nav(page,'Scope').evaluate(element=>element===document.activeElement)&&await scopeTab(page,'Folders').isVisible());
  await page.keyboard.press('End');check('Workbench End navigation opens History',await nav(page,'History').getAttribute('aria-current')==='page'&&await page.getByRole('heading',{name:'Your conversations',exact:true}).isVisible());await page.keyboard.press('ArrowLeft');check('Workbench previous navigation opens Chat and its true scope context',await nav(page,'Chat').getAttribute('aria-current')==='page'&&(await page.locator('[aria-label="Current chat context"]').innerText()).includes('8 notes in scope')&&(await page.locator('[aria-label="Current chat context"]').innerText()).includes('Connect a model first'));
  await page.keyboard.press('Home');check('Workbench Home navigation returns to Connections',await nav(page,'Connections').getAttribute('aria-current')==='page'&&await nav(page,'Connections').evaluate(element=>element===document.activeElement));
  await page.setViewportSize({width:1200,height:800});await page.evaluate(()=>document.querySelector('.notework-root').style.maxWidth='320px');
  check('Workbench adapts to a narrow Obsidian pane inside a wide window',await page.locator('.nw-subscription-heading').first().evaluate(element=>getComputedStyle(element).flexDirection==='column')&&await page.locator('.notework-root').evaluate(element=>element.scrollWidth<=element.clientWidth));
  await page.evaluate(()=>document.querySelector('.notework-root').style.removeProperty('max-width'));await page.setViewportSize({width:320,height:1000});
  for(const view of ['Connections','Scope','Knowledge','Chat','History']){await nav(page,view).click();await noOverflow(page,'320 workbench '+view);check('Workbench native controls stay within narrow pane '+view,await page.locator('.nw-content input:not([type=checkbox]),.nw-content textarea,.nw-content select').evaluateAll(elements=>elements.every(element=>{const bounds=element.getBoundingClientRect();return bounds.left>=0&&bounds.right<=innerWidth+1;})));}
  await page.setViewportSize({width:980,height:1000});await nav(page,'Connections').click();
}
async function listingScreenshot(page,name){await languageSnapshot(page);await page.evaluate(()=>window.scrollTo(0,0));const file=path.join(out,name+'.png');await page.screenshot({path:file,fullPage:false});report.screenshots.push(file);check('Community listing screenshot stays below 5 MiB '+name,fs.statSync(file).size<5*1024*1024);}
async function designShowcase(page){
  const previous=await page.evaluate(()=>{const state=window.fixture.controller.state;return {draft:state.draft,answer:state.answer,status:state.status};});
  await page.setViewportSize({width:1200,height:800});await nav(page,'Connections').click();await btn(page,'Short connection test').click();await settled(page);await listingScreenshot(page,'listing-connections');
  await nav(page,'Scope').click();await page.locator('[data-focus-id="scope-filter"]').fill('Research');await listingScreenshot(page,'listing-scope');await page.locator('[data-focus-id="scope-filter"]').fill('');
  await page.evaluate(()=>window.fixture.controller.set({draft:'How do ontology and graph retrieval connect?',answer:'Ontology organizes concepts and their relationships. Graph retrieval connects those relationships to evidence in the source notes. Start with a small note scope and open the original notes to inspect the connections.',status:'Example answer using synthetic source notes.'}));
  await nav(page,'Chat').click();await listingScreenshot(page,'listing-chat');
  await page.setViewportSize({width:360,height:1000});
  for(const view of ['Connections','Scope','Chat']){await nav(page,view).click();await noOverflow(page,'360 design '+view);await shot(page,'design-'+view.toLowerCase()+'-360-light');}
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.evaluate(()=>{document.documentElement.style.setProperty('--text-normal','#e7eaf0');document.documentElement.style.setProperty('--text-muted','#b7bdc9');document.documentElement.style.setProperty('--text-accent','#86afff');document.documentElement.style.setProperty('--background-modifier-hover','#303848');document.documentElement.style.setProperty('--background-primary','#181c26');document.documentElement.style.setProperty('--background-secondary','#232936');document.documentElement.style.setProperty('--background-modifier-border','#3a4354');document.body.style.background='#181c26';});
  for(const view of ['Connections','Scope','Chat']){await nav(page,view).click();await noOverflow(page,'360 design dark '+view);await shot(page,'design-'+view.toLowerCase()+'-360-dark');}
  await page.setViewportSize({width:980,height:1000});await nav(page,'Chat').click();
  const contrast=await page.evaluate(()=>{function lum(value){const values=value.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);});return .2126*values[0]+.7152*values[1]+.0722*values[2];}function ratio(a,b){const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}const tab=getComputedStyle(document.querySelector('.nw-tabs [aria-current=page]')),link=getComputedStyle(document.querySelector('.nw-sources button')),body=getComputedStyle(document.body);return {selectedTab:ratio(tab.color,tab.backgroundColor),sourceLink:ratio(link.color,body.backgroundColor)};});
  check('Dark workbench selected tab and source links remain readable on hover',contrast.selectedTab>=4.5&&contrast.sourceLink>=4.5,contrast);await shot(page,'design-chat-desktop-dark');
  await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});await page.evaluate(()=>{for(const key of ['--text-normal','--text-muted','--text-accent','--background-modifier-hover','--background-primary','--background-secondary','--background-modifier-border'])document.documentElement.style.removeProperty(key);document.body.style.removeProperty('background');});await nav(page,'Chat').click();
  await page.evaluate(saved=>window.fixture.controller.set(saved),previous);
}
async function verifyChatGPT(page){await nav(page,'Connections').click();await btn(page,'Continue with ChatGPT').click();await settled(page);await btn(page,'Short connection test').click();await settled(page);}
async function claudeCardLayout(page,label){
  const card=page.getByRole('region',{name:'Claude Code subscription',exact:true});
  check('Claude login actions belong to the Claude card '+label,await card.getByRole('button',{name:'Sign in with Claude subscription',exact:true}).isVisible()&&await card.getByRole('button',{name:'Use existing Claude Code login',exact:true}).isVisible()&&await btn(page,'Sign in with Claude subscription').count()===1);
  check('Claude card precedes optional API and local panels '+label,await page.evaluate(()=>{const card=document.querySelector('[data-provider="claude-code"]');const optional=Array.from(document.querySelectorAll('.nw-content>details')).filter(x=>['Connect with an API key','Connect a local model'].includes(x.querySelector('summary')?.textContent));return optional.length===2&&optional.every(x=>card.compareDocumentPosition(x)&Node.DOCUMENT_POSITION_FOLLOWING);}));
  if((await state(page)).mode==='claude-code'){
    check('Claude status installation and model controls remain inside its card '+label,await card.locator('[aria-label="Claude connection status"]').count()===1&&await card.locator('.nw-claude-installation').count()===1&&await card.locator('.nw-current').count()===1&&await card.getByRole('button',{name:'Short connection test',exact:true}).count()===1&&await page.locator('.nw-content>.nw-current').count()===0);
    const relevant=await page.locator('.nw-claude-status button,.nw-claude-installation button,.nw-current button').evaluateAll(buttons=>buttons.map(button=>({label:button.textContent,provider:button.closest('[data-provider]')?.dataset.provider})));
    check('All Claude account status and model action buttons have the same card owner '+label,relevant.length>0&&relevant.every(button=>button.provider==='claude-code'),relevant);
  }
}
async function claudeConnectionUX(page){
  await claudeCardLayout(page,'before selection');
  await page.evaluate(()=>window.fixture.control.connectBehaviors.codex='waiting');
  const chatModelsBefore=await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.mode==='codex'&&x.type==='listModels').length);
  await btn(page,'Continue with ChatGPT').click();
  await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.status.includes('synthetic ChatGPT sign-in'));
  check('Pending ChatGPT keeps Claude connect actionable',await btn(page,'Use existing Claude Code login').isEnabled()&&await btn(page,'Continue with ChatGPT').isDisabled());
  check('Provider switch explains pending task cancellation',(await page.locator('.nw-subscription-actions').last().innerText()).includes('stops the current operation'));
  await shot(page,'00-chatgpt-pending-claude-switch');
  await btn(page,'Use existing Claude Code login').click();await settled(page);
  check('Claude switch aborts old ChatGPT login and connects selected provider',(await state(page)).mode==='claude-code'&&(await state(page)).connection==='catalog-confirmed'&&await page.evaluate(()=>window.fixture.trace.calls.some(x=>x.mode==='codex'&&x.type==='connect-aborted')));
  check('Existing Claude Code login action does not force account sign-in',await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.mode==='claude-code'&&x.type==='connect').at(-1).newAccount===false));
  await claudeCardLayout(page,'connected');await shot(page,'00-claude-card-connected-desktop');await page.setViewportSize({width:390,height:1000});await claudeCardLayout(page,'connected mobile');await noOverflow(page,'390 grouped Claude card');await shot(page,'00-claude-card-connected-mobile');await page.setViewportSize({width:980,height:1000});
  check('Aborted ChatGPT never lists models',await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.mode==='codex'&&x.type==='listModels').length)===chatModelsBefore);
  await page.waitForTimeout(220);check('Late cancelled login callback cannot replace Claude connection',(await state(page)).connection==='catalog-confirmed'&&!(await state(page)).status.includes('LATE_CANCELLED_LOGIN_STATUS'));
  await page.evaluate(()=>window.fixture.control.connectBehaviors['claude-code']='notFound');
  await btn(page,'Use existing Claude Code login').click();await settled(page);
  check('Missing CLI reports specific failure state',(await state(page)).connection==='failed'&&(await state(page)).connectionIssue==='CLI_NOT_FOUND');
  const help=page.locator('[aria-label="Claude connection status"]');
  check('Missing CLI has visible inline installation and retry guidance',await help.isVisible()&&(await help.innerText()).includes('executable not found')&&await help.getByRole('button',{name:'Official Claude Code setup',exact:true}).isVisible()&&await help.getByRole('button',{name:'Retry Claude connection',exact:true}).isEnabled());
  await claudeCardLayout(page,'missing CLI');
  check('Manual install paths are optional and collapsed',!await page.locator('details').filter({has:page.locator('summary').filter({hasText:/^Specify installation path$/})}).evaluate(x=>x.open));
  await shot(page,'00-claude-not-found-desktop');await noOverflow(page,'980 missing Claude');
  await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 missing Claude');await shot(page,'00-claude-not-found-mobile');await page.setViewportSize({width:980,height:1000});
  await btn(page,'Official Claude Code setup').click();
  check('Install help opens the official setup callback only',await page.evaluate(()=>window.fixture.trace.links.at(-1)==='https://code.claude.com/docs/en/setup'));
  await page.evaluate(()=>window.fixture.control.connectBehaviors['claude-code']='normal');await btn(page,'Retry Claude connection').click();await settled(page);
  check('Retry after installation clears failure and returns host-managed model',(await state(page)).connection==='catalog-confirmed'&&(await state(page)).connectionIssue===''&&(await state(page)).model==='fixture-host-managed-default');
  await page.evaluate(()=>window.fixture.control.connectBehaviors['claude-code']='waiting');
  await btn(page,'Sign in with Claude subscription').click();
  await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.loginUrl);
  check('Primary Claude subscription login forwards newAccount',await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.mode==='claude-code'&&x.type==='connect').at(-1).newAccount===true));
  check('Current official Claude authorization host path and boolean code switch remain actionable',await page.evaluate(()=>{const url=new URL(window.fixture.controller.state.loginUrl);return url.hostname==='claude.com'&&url.pathname==='/cai/oauth/authorize'&&url.searchParams.get('code')==='true';})&&await btn(page,'Open Claude login again').isEnabled());
  await claudeCardLayout(page,'waiting for browser sign-in');
  check('Official temporary login URL is actionable during waiting',(await state(page)).connectionPhase==='waiting-login'&&await btn(page,'Open Claude login again').isVisible()&&await btn(page,'Stop Claude connection').isEnabled());
  await btn(page,'Open Claude login again').click();
  check('Reopen passes the current official HTTPS URL to host callback',await page.evaluate(()=>window.fixture.trace.links.at(-1)===window.fixture.control.loginUrl));
  check('Temporary login URL is absent from persisted settings',await page.evaluate(()=>window.fixture.trace.savedSettings.every(x=>!JSON.stringify(x).includes('fixture_nonce'))));
  const codeDetails=await details(page,'Browser shows a login code?');const codeInput=page.getByLabel('Claude authorization code',{exact:true});
  check('Official code fallback belongs to Claude card and stays masked',await codeDetails.evaluate(element=>element.closest('[data-provider]')?.dataset.provider==='claude-code')&&await codeInput.getAttribute('type')==='password'&&await codeInput.getAttribute('autocomplete')==='off'&&await btn(page,'Complete Claude sign-in').isDisabled());
  await codeInput.fill('synthetic-code-fixture-only');await page.evaluate(()=>window.fixture.controller.set({status:'Waiting for synthetic sign-in with optional browser code.'}));
  check('Ordinary waiting updates preserve transient input and open fallback',await codeInput.inputValue()==='synthetic-code-fixture-only'&&await codeDetails.evaluate(element=>element.open));
  check('Authorization input is absent from settings controller state and saved secrets',await page.evaluate(()=>!JSON.stringify(window.fixture.controller.settings).includes('synthetic-code-fixture-only')&&!JSON.stringify(window.fixture.controller.state).includes('synthetic-code-fixture-only')&&window.fixture.trace.savedSettings.every(value=>!JSON.stringify(value).includes('synthetic-code-fixture-only'))&&window.fixture.memory.size===0));
  await btn(page,'Complete Claude sign-in').click();await page.waitForFunction(()=>window.fixture.trace.calls.some(call=>call.type==='submit-login-code'));
  check('Code completion forwards only to selected synthetic Claude process',await page.evaluate(()=>window.fixture.trace.calls.filter(call=>call.type==='submit-login-code').every(call=>call.mode==='claude-code'&&call.receivedSyntheticCode)));
  check('Submitting clears authorization input immediately',await codeInput.inputValue()===''&&await btn(page,'Complete Claude sign-in').isDisabled()&&await page.evaluate(()=>window.fixture.ui.claudeLoginCode===''));
  await codeInput.fill('synthetic-code-fixture-only');
  await shot(page,'00-claude-login-waiting-desktop');await noOverflow(page,'980 Claude login');
  await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 Claude login');await shot(page,'00-claude-login-waiting-mobile');await page.setViewportSize({width:980,height:1000});
  await btn(page,'Stop Claude connection').click();
  check('Claude cancel clears busy phase and temporary URL',!(await state(page)).busy&&(await state(page)).loginUrl===''&&(await state(page)).connectionPhase===''&&(await status(page).innerText()).includes('Operation stopped')&&await btn(page,'Open Claude login again').count()===0);
  check('Stopping removes and wipes pending authorization code',await codeInput.count()===0&&await page.evaluate(()=>window.fixture.ui.claudeLoginCode===''&&!window.fixture.ui.claudeCodeOpen));
  await page.waitForTimeout(220);check('Cancelled Claude login cannot restore old URL',!(await state(page)).busy&&(await state(page)).loginUrl===''&&!(await state(page)).status.includes('LATE_CANCELLED_LOGIN_STATUS'));
  await btn(page,'Sign in with Claude subscription').click();await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.loginUrl);await page.evaluate(()=>window.fixture.controller.set({loginCodeRequired:true}));
  check('Official CLI code requirement opens its optional fallback automatically',await page.locator('.nw-claude-code').evaluate(element=>element.open)&&await codeInput.isVisible());
  await codeInput.fill('synthetic-code-fixture-only');await btn(page,'Continue with ChatGPT').click();await page.waitForFunction(()=>window.fixture.controller.state.mode==='codex');
  check('Switching provider removes and wipes pending Claude authorization input',await codeInput.count()===0&&await page.evaluate(()=>window.fixture.ui.claudeLoginCode===''&&!window.fixture.ui.claudeCodeOpen));await btn(page,'Stop').click();
  for(const invalidUrl of ['http://claude.ai/oauth/authorize?fixture_nonce=qa-only','https://claude.ai.attacker.invalid/oauth/authorize','https://qa-only@claude.ai/oauth/authorize','https://claude.com.attacker.invalid/cai/oauth/authorize?code=true','https://claude.com/cai/oauth/callback?code=synthetic-returned-code','https://claude.com/cai/oauth/authorize?code=synthetic-returned-code']) {
    await page.evaluate(url=>window.fixture.control.loginUrl=url,invalidUrl);await btn(page,'Use existing Claude Code login').click();
    await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.connectionPhase==='waiting-login');
    check('Nonofficial or credential-bearing login URL withheld '+invalidUrl,(await state(page)).loginUrl===''&&await btn(page,'Open Claude login again').count()===0);
    await btn(page,'Stop Claude connection').click();
  }
  await page.evaluate(()=>{window.fixture.control.loginUrl='https://auth.claude.ai/oauth/authorize?fixture_nonce=qa-only';window.fixture.control.loginDelayMs=350;});
  await btn(page,'Use existing Claude Code login').click();await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.loginUrl);
  check('Official auth subdomain login URL accepted',(await state(page)).loginUrl.startsWith('https://auth.claude.ai/'));
  await settled(page);
  check('Successful Claude login clears temporary URL and failure state',(await state(page)).connection==='catalog-confirmed'&&(await state(page)).connectionPhase==='connected'&&(await state(page)).loginUrl===''&&(await state(page)).connectionIssue===''&&await btn(page,'Open Claude login again').count()===0);
  check('Completed sign-in has no authorization input or remembered code',await codeInput.count()===0&&await page.evaluate(()=>window.fixture.ui.claudeLoginCode===''));
  await page.evaluate(()=>{window.fixture.control.connectBehaviors.codex='normal';window.fixture.control.connectBehaviors['claude-code']='normal';window.fixture.control.loginDelayMs=5000;window.fixture.control.loginUrl='https://claude.com/cai/oauth/authorize?code=true&fixture_nonce=qa-only';});
  await btn(page,'Continue with ChatGPT').click();await settled(page);
  await btn(page,'Sign in with Claude subscription').click();await settled(page);
  check('Primary Claude sign-in selects Claude from another provider and forces official account login',(await state(page)).mode==='claude-code'&&await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.mode==='claude-code'&&x.type==='connect').at(-1).newAccount===true));
  await btn(page,'Continue with ChatGPT').click();await settled(page);
  check('Synthetic login checks never invoke inference or real credentials',await page.evaluate(()=>window.fixture.trace.calls.every(x=>x.type!=='generate')&&window.fixture.memory.size===0));
}
async function run(page,origin){
  page.on('pageerror',e=>report.pageErrors.push(String(e)));
  page.on('request',r=>{if(/^https?:/i.test(r.url())&&!r.url().startsWith(origin+'/'))report.externalRequests.push(r.url());});
  page.on('download',d=>report.downloads.push(d.suggestedFilename()));page.on('popup',p=>report.popups.push(p.url()));
  await page.goto(origin+'/tests/ui-fixture.html');await page.waitForFunction(()=>window.fixtureReady);
  check('Plugin contains no donation icon or link',await page.locator('.nw-support,.nw-coffee-link,a[href*=buymeacoffee]').count()===0);
  await workbenchDesignUX(page);
  check('Production controller starts ChatGPT subscription',(await state(page)).mode==='codex');
  check('Two subscription choices appear first',await page.locator('.nw-subscription-heading h3').allTextContents().then(x=>x.join('|')==='ChatGPT subscription|Claude Code subscription'));
  const api=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Connect with an API key'})});
  check('API connection controls remain visible before verification',await api.evaluate(x=>x.open));check('No LLM API password field initially',await page.locator('[data-focus-id="key-openai"],[data-focus-id="key-anthropic"]').count()===0);
  await noOverflow(page,'980 connection');await shot(page,'01-connection-desktop');await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 connection');await shot(page,'01-connection-mobile');await page.setViewportSize({width:980,height:1000});
  await claudeConnectionUX(page);
  await nav(page,'Chat').click();await question(page,'Ontology');await consent(page,true);check('Verification required to enable chat',await btn(page,'Send question').isDisabled());
  await nav(page,'Connections').click();await btn(page,'Continue with ChatGPT').click();await settled(page);
  const c=await state(page);check('Subscription button invokes actual controller connect/list',await page.evaluate(()=>window.fixture.trace.calls.some(x=>x.mode==='codex'&&x.type==='connect')&&window.fixture.trace.calls.some(x=>x.mode==='codex'&&x.type==='listModels')));
  check('Catalog contains dynamic fixture-only model',c.model==='gpt-6.1-sol'&&c.models.some(x=>x.id==='tenant-model-zeta-2049')&&await page.locator('.nw-current select:first-of-type option').allTextContents().then(x=>x.includes('Synthetic account model Zeta')));
  check('Listing does not mark inference verified',c.connection==='catalog-confirmed'&&!c.verified&&!c.consent);
  await nav(page,'Chat').click();await consent(page,true);check('Catalog-only chat remains locked',await btn(page,'Send question').isDisabled());await nav(page,'Connections').click();
  await btn(page,'Short connection test').click();await settled(page);check('Short inference unlocks selected model',(await state(page)).verified&&(await state(page)).connection==='inference-confirmed');
  check('Verification contains no note context',await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.type==='generate'&&x.verify).every(x=>!x.input.includes('<note')&&!x.input.includes('ALLOWED_'))));
  await page.locator('.nw-current select').first().selectOption('tenant-model-zeta-2049');check('Model change invalidates verify and consent without inference',!(await state(page)).verified&&!(await state(page)).consent);await page.locator('.nw-current select').first().selectOption('gpt-6.1-sol');await btn(page,'Short connection test').click();await settled(page);
  await nav(page,'Chat').click();await consent(page,true);await nav(page,'Connections').click();await btn(page,'Use existing Claude Code login').click();await settled(page);
  check('Claude subscription invokes its controller adapter',(await state(page)).mode==='claude-code'&&await page.evaluate(()=>window.fixture.trace.calls.some(x=>x.mode==='claude-code'&&x.type==='connect')));
  check('Mode change resets previous consent and verification',!(await state(page)).verified&&!(await state(page)).consent);
  check('Claude runtime catalog stays separate from API catalogs and explains account access verification',(await state(page)).model==='fixture-host-managed-default'&&(await state(page)).models.every(model=>!model.id.startsWith('api-fixture-'))&&await page.locator('.nw-current').evaluate(element=>{const copy=element.textContent;return copy.includes('installed official Claude Code runtime')&&copy.includes('Update Claude Code and refresh')&&copy.includes('connection test checks access with your signed-in account');}));
  const claude=await details(page,'Specify installation path');
  const fields=claude.locator('input');await fields.nth(0).fill('C:/Synthetic/claude.exe');await fields.nth(1).fill('C:/Synthetic/cli.js');await fields.nth(2).fill('C:/Synthetic/node.exe');
  await btn(page,'Apply installation path').click();await page.waitForFunction(()=>window.fixture.trace.configs.length===1);check('Claude path draft passed to host configuration',await page.evaluate(()=>window.fixture.trace.configs[0].executablePath==='C:/Synthetic/claude.exe'&&window.fixture.trace.configs[0].cliJsPath==='C:/Synthetic/cli.js'));
  await details(page,'Specify installation path');check('Claude path draft survives a production re-render',await page.locator('details').filter({has:page.locator('summary').filter({hasText:'Specify installation path'})}).locator('input').nth(0).inputValue()==='C:/Synthetic/claude.exe');
  await details(page,'Connect with an API key');await btn(page,'Use OpenAI API').click();await settled(page);check('Explicit API selection changes actual controller mode',(await state(page)).mode==='openai'&&await page.locator('[data-focus-id="key-openai"]').getAttribute('type')==='password');
  await btn(page,'Save key').click();await page.waitForFunction(()=>window.fixture.controller.state.status.includes('Enter your API key'));check('Empty key shows actionable feedback',(await status(page).innerText()).includes('Enter your API key'));
  const fakeKey='qa-only-synthetic-key';await page.locator('[data-focus-id="key-openai"]').fill(fakeKey);await page.evaluate(()=>window.fixture.control.storageFailure=true);await btn(page,'Save key').click();await page.waitForFunction(()=>window.fixture.controller.state.status.includes('Failed to save'));check('Secret-store failure reaches status feedback',(await status(page).innerText()).includes('Failed to save credentials'));
  await page.evaluate(()=>window.fixture.control.storageFailure=false);await btn(page,'Save key').click();await page.waitForFunction(()=>window.fixture.controller.state.status.startsWith('Key saved'));check('Saved API key clears password UI',await page.locator('[data-focus-id="key-openai"]').inputValue()==='');
  await btn(page,'Load models').click();await settled(page);check('API catalogs are dynamic',(await state(page)).model==='api-fixture-openai-unique');await shot(page,'02-api-expanded-desktop');
  check('Key absent from text and web storage',!(await page.locator('body').innerText()).includes(fakeKey)&&await page.evaluate(()=>localStorage.length===0&&sessionStorage.length===0));
  await verifyChatGPT(page);await scopeUX(page);await nav(page,'Chat').click();await consent(page,true);await nav(page,'Scope').click();
  check('Scope explains current active vault',(await page.locator('.nw-content').innerText()).includes('To use another vault, open it in Obsidian'));
  await page.locator('[data-focus-id="scope-all"]').uncheck();await scopeCheckbox(page,'Research',true);await scopeCheckbox(page,'Research/Methods',true);await page.locator('[data-focus-id="scope-exclude"]').fill('Research/private');await btn(page,'Apply scope').click();await settled(page);
  const scoped=await state(page);check('Applying scope resets consent',!scoped.consent&&scoped.tab==='chat'&&scoped.scope.mode==='folders');check('Selected scope honors boundaries and exclusion',await page.evaluate(()=>window.fixture.controller.scopeFiles().map(x=>x.path).sort().join('|')==='Research/Methods/graph.md|Research/huge.md|Research/ontology.md|Research/unmatched.md'));
  await nav(page,'Scope').click();await shot(page,'03-scope-desktop');await noOverflow(page,'980 scope');await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 scope');await shot(page,'03-scope-mobile');await page.setViewportSize({width:980,height:1000});await nav(page,'Chat').click();
  await question(page,'Ontology');check('Scope change keeps explicit Send available after model verification',await btn(page,'Send question').isEnabled()&&!(await state(page)).consent);await consent(page,true);await btn(page,'Send question').click();
  await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.answer.includes('First part'));check('Live streamed delta renders before completion',(await page.locator('[aria-label="AI answer"]').innerText()).includes('First part')&&(await state(page)).busy);await settled(page);
  const answer=await state(page);check('Streamed complete answer displayed',answer.answer==='First part of the synthetic answer and its continuation.'&&await page.locator('[aria-label="AI answer"]').innerText()===answer.answer);
  check('Workbench chat context reflects the selected model and accepted note scope',await page.evaluate(()=>{const controller=window.fixture.controller,context=document.querySelector('[aria-label="Current chat context"]').textContent;return context.includes(controller.state.models.find(model=>model.id===controller.state.model).name)&&context.includes(controller.scopeFiles().length+' notes in scope');}));
  check('Retrieved sources only allowed note paths',answer.sources.map(x=>x.path).sort().join('|')==='Research/Methods/graph.md|Research/ontology.md');
  const prompt=await page.evaluate(()=>window.fixture.trace.calls.filter(x=>x.type==='generate'&&!x.verify).at(-1).input);check('Provider context excludes private sibling system and oversize markers',prompt.includes('ALLOWED_ONTOLOGY')&&prompt.includes('ALLOWED_GRAPH')&&!/EXCLUDED_PRIVATE_MARKER|SIBLING_BOUNDARY_MARKER|OUTSIDE_PRIVATE_MARKER|SYSTEM_MARKER|OVERSIZE_MARKER/.test(prompt));
  check('Retrieval read only the selected bounded notes',await page.evaluate(()=>window.fixture.trace.reads.every(p=>['Research/ontology.md','Research/Methods/graph.md','Research/unmatched.md'].includes(p))));
  await btn(page,answer.sources[0].path).click();check('Source button opens its matching note callback',await page.evaluate(()=>window.fixture.trace.opened[0]===window.fixture.controller.state.sources[0].path));await shot(page,'04-chat-desktop');await noOverflow(page,'980 chat');await page.setViewportSize({width:390,height:1000});await noOverflow(page,'390 chat');await shot(page,'04-chat-mobile');await page.setViewportSize({width:980,height:1000});
  await designShowcase(page);
  await page.evaluate(()=>window.fixture.control.behavior='slow');await question(page,'Ontology cancellation');await btn(page,'Send question').click();await page.waitForFunction(()=>window.fixture.controller.state.busy&&window.fixture.controller.state.answer.includes('delayed'));await btn(page,'Stop').click();check('Cancel clears busy and displays stopped status',!(await state(page)).busy&&(await status(page).innerText()).includes('Operation stopped'));await page.waitForTimeout(300);check('Late cancelled delta cannot overwrite UI',!(await state(page)).answer.includes('LATE_ABORTED_DELTA'));
  const apiCallsBefore=await page.evaluate(()=>window.fixture.trace.calls.filter(x=>['openai','anthropic'].includes(x.mode)).length);await page.evaluate(()=>window.fixture.control.behavior='quota');await question(page,'Ontology quota');await btn(page,'Send question').click();await settled(page);check('Quota error is shown in production status',(await status(page).innerText()).includes('Subscription usage limit reached'));check('Quota never falls back to an API provider',(await state(page)).mode==='codex'&&await page.evaluate(()=>window.fixture.trace.calls.filter(x=>['openai','anthropic'].includes(x.mode)).length)===apiCallsBefore);
  await nav(page,'Scope').click();await page.locator('[data-focus-id="scope-exclude"]').fill('../Private');await btn(page,'Apply scope').click();await page.waitForFunction(()=>window.fixture.controller.state.status.includes('within the current vault'));check('Scope rejects traversal without changing accepted scope',(await state(page)).scope.exclude.join('|')==='Research/private'&&(await status(page).innerText()).includes('a folder within the current vault'));
  await knowledgeHistoryUX(page);await languageSnapshot(page);check('Application-owned static strings and synthetic UI are English-only',report.languageViolations.length===0,report.languageViolations);
  check('No browser runtime errors',report.pageErrors.length===0,report.pageErrors);check('No external requests',report.externalRequests.length===0,report.externalRequests);check('No downloads or login popups',report.downloads.length===0&&report.popups.length===0);
}
if(require.main===module)(async()=>{let browser,server;try{const routes=new Map([['/tests/ui-fixture.html','tests/ui-fixture.html'],['/styles.css','styles.css'],['/src/ui.mjs','src/ui.mjs'],['/src/knowledge-space.mjs','src/knowledge-space.mjs'],['/src/controller.mjs','src/controller.mjs'],['/src/model-options.mjs','src/model-options.mjs'],['/src/conversation-flow.mjs','src/conversation-flow.mjs'],['/src/providers/claude-login-url.mjs','src/providers/claude-login-url.mjs'],['/src/providers/codex-login-url.mjs','src/providers/codex-login-url.mjs'],['/src/vault-search.mjs','src/vault-search.mjs'],['/src/runtime-storage.mjs','src/runtime-storage.mjs'],['/src/portable-crypto.mjs','src/portable-crypto.mjs'],['/src/archive-paths.mjs','src/archive-paths.mjs']]);for(const name of ['setup-guide','conversation-map','conversation-structure','index-coverage','knowledge-engine','note-preview'])routes.set('/src/'+name+'.mjs','src/'+name+'.mjs');for(const name of ['ollama-embeddings','jev'])routes.set('/src/providers/'+name+'.mjs','src/providers/'+name+'.mjs');server=http.createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');report.serverRequests.push(url.pathname);const target=routes.get(url.pathname);if(!target){res.writeHead(404);res.end('Not found');return;}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',target.endsWith('.html')?'text/html; charset=utf-8':target.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(root,target)));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-gpu']});const context=await browser.newContext({viewport:{width:980,height:1000}});const page=await context.newPage();await attachKnowledgeBridge(page);await run(page,origin);report.passed=true;}catch(error){report.passed=false;report.failure=String(error);process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));report.finishedAt=new Date().toISOString();report.productionModulesAtEnd=Object.fromEntries(sources.map(p=>[p,sha(path.join(root,p))]));report.sourceChangedDuringRun=JSON.stringify(report.productionModules)!==JSON.stringify(report.productionModulesAtEnd);fs.writeFileSync(path.join(out,'ui-report.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify({passed:report.passed,checks:report.checks.length,failed:report.checks.filter(x=>!x.passed).length,failure:report.failure,screenshots:report.screenshots.length,sourceChangedDuringRun:report.sourceChangedDuringRun,productionModules:report.productionModules,report:path.join(out,'ui-report.json')},null,2));}})();






module.exports={attachKnowledgeBridge};
