const fs=require('fs');
const path=require('path');
const http=require('http');
const crypto=require('crypto');
const {chromium}=require(process.env.NOTEWORK_PLAYWRIGHT_PATH||'playwright');
const {attachKnowledgeBridge}=require('./ui-qa.cjs');
const project=path.resolve(__dirname,'..');
const output=process.env.NOTEWORK_QA_OUTPUT||path.join(project,'qa-output','workspace');
fs.mkdirSync(output,{recursive:true});
const tracked=['src/ui.mjs','styles.css','src/knowledge-space.mjs','src/note-preview.mjs','src/controller.mjs','src/conversation-flow.mjs','src/conversation-archive.mjs','src/knowledge-engine.mjs'];
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(project,file))).digest('hex');
const report={startedAt:new Date().toISOString(),productionModules:Object.fromEntries(tracked.map(file=>[file,digest(file)])),checks:[],screenshots:[],pageErrors:[],externalRequests:[],downloads:[],popups:[],languageViolations:[],limitations:['Production settings, sidebar and workspace UI/controller run unchanged with synthetic vault, model catalog, accounts and typed Jev results.','KnowledgeEngine and ConversationArchive run unchanged in Node over a local bridge with synthetic embeddings.','Illustrative editor/file-tree framing in sidebar screenshots is a test fixture; the Notework UI inside is production code.','No real authentication, user vault notes, Jev/cloud calls or model downloads.']};
function check(name,value,detail){report.checks.push({name,passed:!!value,...(detail===undefined?{}:{detail})});if(!value)throw Error(name+': '+JSON.stringify(detail));}
const btn=(page,name)=>page.getByRole('button',{name,exact:true});
async function chooseStar(page,name,options={}){const close=page.getByRole('button',{name:'Close note preview',exact:true});if(await close.count())await close.click();const id=await page.getByRole('button',{name:'Select note '+name,exact:true}).getAttribute('data-node-id');const point=await page.locator('.nw-space-canvas').evaluate((canvas,id)=>JSON.parse(canvas.dataset.projection).find(star=>star.id===id),id);await page.locator('.nw-space-canvas').click({position:{x:point.x,y:point.y},...options});}
const nav=(page,name)=>page.locator('.nw-tabs').getByRole('button',{name,exact:true});
const settled=page=>page.waitForFunction(()=>window.fixtureReady&&!window.fixture.controller.state.busy);
async function state(page){return page.evaluate(()=>structuredClone(window.fixture.controller.state));}
async function language(page){const violations=await page.evaluate(()=>[...document.querySelectorAll('.notework-root')].flatMap(root=>[root.textContent,...[...root.querySelectorAll('[aria-label],[placeholder]')].map(el=>[el.getAttribute('aria-label'),el.getAttribute('placeholder')].join(' '))]).filter(text=>/[\uac00-\ud7a3]/u.test(text)));report.languageViolations.push(...violations);}
async function shot(page,name){await language(page);check('No donation icon or link in '+name,await page.locator('.nw-support,.nw-coffee-link,a[href*=buymeacoffee]').count()===0);const file=path.join(output,name+'.png');await page.screenshot({path:file,fullPage:false});report.screenshots.push(file);}
async function noOverflow(page,name){const result=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,roots:[...document.querySelectorAll('.notework-root')].map(el=>({width:el.clientWidth,scroll:el.scrollWidth}))}));check('No horizontal overflow: '+name,result.document<=result.width+1&&result.roots.every(root=>root.scroll<=root.width+1),result);}
async function mount(page,surface,{width,framed=false}={}){
  await page.evaluate(({surface,width,framed})=>{const fixture=window.fixture;fixture.ui.destroy();document.querySelector('.fixture-shell')?.remove();const app=document.getElementById('app');app.replaceChildren();app.className='';delete app.dataset.surface;delete app.dataset.view;app.removeAttribute('style');app.style.height='calc(100vh - 35px)';app.style.width=width?width+'px':'100%';app.style.margin='0 auto';let target=app;
    if(framed){const shell=document.createElement('div');shell.className='fixture-shell';shell.style.cssText='height:100%;display:grid;grid-template-columns:165px minmax(0,1fr) 390px;background:var(--background-primary);';const tree=document.createElement('aside');tree.style.cssText='padding:24px 14px;background:var(--background-secondary);border-right:1px solid var(--background-modifier-border);font-size:12px;line-height:2;color:var(--text-muted)';tree.textContent='Synthetic vault\n\nResearch\n  ontology.md\n  Methods\n    graph.md\nNotework\n  Chats';tree.style.whiteSpace='pre-wrap';const editor=document.createElement('article');editor.style.cssText='padding:38px 40px;overflow:hidden';const title=document.createElement('h1');title.textContent='Ontology and source evidence';title.style.cssText='font-size:27px;line-height:1.3;margin:0 0 24px';const copy=document.createElement('p');copy.textContent='An ontology connects concepts, relationships, and evidence. Explore the related notes in Notework, then ask a question about the selected material.';copy.style.cssText='font-size:16px;line-height:1.85;max-width:45ch';const quote=document.createElement('blockquote');quote.textContent='Synthetic example note for interface testing. The sidebar uses the actual production Notework UI.';quote.style.cssText='margin:28px 0;padding:14px 18px;border-left:3px solid #526db5;background:var(--background-secondary);font-size:13px;line-height:1.8;color:var(--text-muted)';editor.append(title,copy,quote);target=document.createElement('div');target.style.cssText='min-width:0;height:100%;border-left:1px solid var(--background-modifier-border);';shell.append(tree,editor,target);app.append(shell);}
    fixture.ui=fixture.mount(surface,target);
  },{surface,width,framed});
}
async function run(page,origin){
  page.on('pageerror',error=>report.pageErrors.push(String(error)));page.on('request',request=>{if(/^https?:/i.test(request.url())&&!request.url().startsWith(origin+'/'))report.externalRequests.push(request.url());});page.on('download',download=>report.downloads.push(download.suggestedFilename()));page.on('popup',popup=>report.popups.push(popup.url()));
  await page.goto(origin+'/tests/ui-fixture.html?surface=settings');await page.waitForFunction(()=>window.fixtureReady);
  check('Settings contain only configuration tabs',(await page.locator('.nw-tabs button').allTextContents()).join('|')==='Setup|Connections|Local embeddings|Scope|Build|Archive');
  check('Settings contain no question composer or runtime graph',await page.locator('[data-focus-id=question],.nw-map-viewport,.nw-history-list').count()===0);
  const initialCalls=await page.evaluate(()=>window.fixture.trace.calls.length);await nav(page,'Archive').click();check('Archive folder and opt-in auto-save are configuration controls',await page.locator('[data-focus-id=archive-folder]').count()===1&&!await page.getByRole('checkbox',{name:'Save after every answer',exact:true}).isChecked());
  await nav(page,'Build').click();check('Build settings contain routes and budget but no knowledge map',await page.locator('[data-focus-id=knowledge-embedding-route],[data-focus-id=knowledge-max-calls]').count()===2&&await page.locator('.nw-map-viewport').count()===0);check('Opening configuration never invokes model requests',await page.evaluate(()=>window.fixture.trace.calls.length)===initialCalls);
  await nav(page,'Connections').click();await btn(page,'Continue with ChatGPT').click();await settled(page);await btn(page,'Short connection test').click();await settled(page);check('Configured model verification is shared with runtime',(await state(page)).verified);
  await page.evaluate(()=>{const host=document.createElement('div');host.id='secondary-panel';host.style.cssText='width:330px;height:720px;position:fixed;right:0;top:35px;background:white';document.body.append(host);window.fixture.side=window.fixture.mount('sidebar',host);window.fixture.side.setView('history');window.fixture.controller.set({tab:'chat',status:'Synthetic shared controller update'});});
  check('Simultaneous settings and sidebar use independent navigation',await page.locator('#app.notework-root').getAttribute('data-view')==='connection'&&await page.locator('#secondary-panel.notework-root').getAttribute('data-view')==='history');
  check('Sidebar never renders connection scope or build controls',await page.locator('#secondary-panel .nw-tabs button').allTextContents().then(names=>names.join('|')==='Chat|History|Conversation map')&&await page.locator('#secondary-panel [data-focus-id=archive-folder],#secondary-panel [data-focus-id=knowledge-embedding-route],#secondary-panel .nw-subscriptions').count()===0);
  await page.evaluate(()=>{window.fixture.side.destroy();document.getElementById('secondary-panel').remove();});
  await page.setViewportSize({width:1200,height:800});await shot(page,'settings-connections-desktop');
  await nav(page,'Scope').click();await page.locator('[data-focus-id=scope-all]').uncheck();await page.getByRole('checkbox',{name:'Include folder Research',exact:true}).check();await page.locator('[data-focus-id=scope-exclude]').fill('Research/private\nResearch/huge.md');await btn(page,'Expand all').click();check('Folder parent selection preserves inherited depth and children',await page.getByRole('checkbox',{name:'Include folder Research/Methods',exact:true}).isChecked()&&(await page.locator('.nw-folder-list').innerText()).includes('Depth 3'));await shot(page,'settings-scope-desktop');await btn(page,'Apply scope').click();
  check('Applying scope stays in configuration and opens Build',await page.locator('.notework-root').getAttribute('data-view')==='build'&&(await state(page)).scope.exclude[0]==='Research/private');
  await page.locator('[data-focus-id=knowledge-embedding-route]').selectOption('ollama');await btn(page,'Load embedding models').click();await settled(page);await page.locator('[data-focus-id=knowledge-embedding-model]').selectOption('synthetic-embedding:local');await page.locator('[data-focus-id=knowledge-semantic-route]').selectOption('llm');await page.getByRole('checkbox',{name:'Limit AI requests',exact:true}).check();await page.locator('[data-focus-id=knowledge-max-calls]').fill('4');await btn(page,'Build knowledge').click();await settled(page);
  const built=await state(page);check('Settings build uses real engine with selected source boundary',built.knowledge.phase==='ready'&&built.knowledge.index.nodes.length===3&&built.knowledge.index.nodes.every(node=>['Research/ontology.md','Research/Methods/graph.md','Research/unmatched.md'].includes(node.path)),built.knowledge);
  check('Successful build offers workspace without showing graph in settings',await btn(page,'Open knowledge workspace').count()===1&&await page.locator('.nw-map-viewport').count()===0);await btn(page,'Open knowledge workspace').click();check('Workspace button calls Obsidian host entry point',await page.evaluate(()=>window.fixture.trace.opened.at(-1).surface==='workspace'));
  await mount(page,'sidebar',{framed:true});check('Runtime defaults to Chat with model selection',await page.locator('.notework-root').getAttribute('data-view')==='chat'&&await page.locator('[data-focus-id=chat-model]').inputValue()==='gpt-6.1-sol');
  check('Compact sidebar omits branding status banners and verified-model tests',await page.locator('.nw-header,.nw-version,.nw-status').count()===0&&await btn(page,'Test chat model').count()===0);
  await page.locator('[data-focus-id=chat-model]').selectOption('tenant-model-zeta-2049');check('An unverified model offers an explicit compact connection test',await btn(page,'Test chat model').isVisible()&&!(await state(page)).verified);await btn(page,'Test chat model').click();await settled(page);check('A successful explicit model test hides the temporary test control',(await state(page)).verified&&await btn(page,'Test chat model').count()===0);await page.locator('[data-focus-id=chat-model]').selectOption('gpt-6.1-sol');await btn(page,'Test chat model').click();await settled(page);
  await btn(page,'Chat with knowledge graph').click();check('Graph expansion invokes dedicated workspace host view',await page.evaluate(()=>window.fixture.trace.opened.at(-1).surface==='workspace'));await btn(page,'Open settings').click();check('Runtime settings button invokes settings host view',await page.evaluate(()=>window.fixture.trace.opened.at(-1).surface==='settings'));
  await page.locator('[data-focus-id=question]').fill('How does ontology organize knowledge?');await btn(page,'Send question').click();await settled(page);check('Sidebar sends real controller retrieval and shows bounded source notes',(await state(page)).messages.length===2&&(await state(page)).sources.every(source=>source.path.startsWith('Research/')&&!source.path.includes('/private/'))&&await page.locator('.nw-answer').count()===1);
  check('Runtime source list is collapsed by default and retained for inspection',await page.locator('.nw-sources').evaluate(el=>el.tagName==='DETAILS'&&!el.open&&el.querySelector('summary').textContent.startsWith('Source notes (')&&el.querySelectorAll('button').length>0));await page.locator('.nw-sources>summary').click();check('Collapsed source list still opens all actual source-note actions',await page.locator('.nw-sources button').first().isVisible());await page.locator('.nw-sources>summary').click();
  check('Runtime displays actual turns directly without a context-wrapper label',await page.locator('.nw-conversation-thread').evaluate(el=>el.tagName==='DIV'&&!el.querySelector('summary')&&el.querySelectorAll('.nw-turn').length>0));check('Built-in prompts stay in a closed composer menu rather than the message feed',await page.locator('.nw-chat-feed .nw-chat-prompts-menu').count()===0&&await page.locator('.nw-chat-composer .nw-chat-prompts-menu').evaluate(el=>!el.open));
  check('Runtime composer remains outside scrollable conversation evidence',await page.locator('.nw-chat-feed [data-focus-id=question]').count()===0&&await page.locator('.nw-chat-composer [data-focus-id=question]').count()===1);check('Sidebar send controls remain inside panel height',await btn(page,'Send question').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));check('Sidebar has no donation icon or link',await page.locator('.nw-support,.nw-coffee-link,a[href*=buymeacoffee]').count()===0);await page.locator('.nw-chat-feed').evaluate(el=>{const answer=el.querySelector('.nw-answer');if(answer)el.scrollTop+=answer.getBoundingClientRect().top-el.getBoundingClientRect().top;});await noOverflow(page,'sidebar in illustrative editor');await shot(page,'sidebar-chat-desktop');
  await mount(page,'workspace');await btn(page,'Whole knowledge').click();await page.waitForFunction(()=>Number(document.querySelector('.nw-space-canvas')?.dataset.stars)===3);
  check('Desktop workspace has graph only and preserves sidebar composition separately',await page.locator('.nw-space-canvas').count()===1&&await page.locator('[data-focus-id=question],.nw-runtime-chat,.nw-workspace-resizer').count()===0);
  check('Workspace graph uses the actual indexed source IDs and depth',await page.locator('.nw-space-canvas').evaluate(canvas=>{const stars=JSON.parse(canvas.dataset.projection);return stars.length===3&&new Set(stars.map(star=>star.id)).size===3&&new Set(stars.map(star=>star.depth)).size===3;}));
  check('Workspace paints compact pale and cyan cores against a dark background',await page.locator('.nw-space-canvas').evaluate(canvas=>{const ctx=canvas.getContext('2d'),background=ctx.getImageData(2,2,1,1).data,ratio=canvas.width/canvas.getBoundingClientRect().width;return JSON.parse(canvas.dataset.projection).every(star=>{const patch=ctx.getImageData(Math.round(star.x*ratio)-3,Math.round(star.y*ratio)-3,7,7).data;let core=0;for(let at=0;at<patch.length;at+=4)if(patch[at+1]>background[1]+30&&patch[at+2]>background[2]+30)core++;return core>0&&core<35;});}));
  await btn(page,'Whole knowledge').click();await btn(page,'Category regions').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('.nw-space-canvas').dataset.regions).includes('Concepts'));check('Semantic grouping comes from actual canvas region data',await page.locator('.nw-map-heading,.nw-space-legend').count()===0&&await page.locator('.nw-space-canvas').evaluate(canvas=>JSON.parse(canvas.dataset.regions).includes('Concepts')));
  const before=await page.locator('.nw-space-canvas').getAttribute('data-projection');await page.locator('.nw-space-canvas').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(60);check('Keyboard orbit changes the real graph projection',await page.locator('.nw-space-canvas').getAttribute('data-projection')!==before);await btn(page,'Reset camera').click();
  await chooseStar(page,'ontology');await page.waitForFunction(()=>document.querySelector('.nw-note-preview-content')?.getAttribute('aria-busy')==='false');check('Graph selection displays the original scoped note and content hash',(await page.locator('.nw-note-preview').innerText()).includes('ALLOWED_ONTOLOGY')&&(await page.locator('.nw-note-preview').innerText()).includes('Content hash:'));await shot(page,'workspace-note-preview-desktop');
  const opened=await page.evaluate(()=>window.fixture.trace.opened.length);await btn(page,'Chat with this selection').click();check('Graph selection requests the existing sidebar through its host callback',await page.evaluate(before=>window.fixture.trace.opened.slice(before).some(item=>item.surface==='sidebar'),opened));
  await mount(page,'sidebar');check('Sidebar retains the composer and model without a mandatory checkbox',await page.locator('[data-focus-id=question]').count()===1&&await page.locator('.nw-chat-composer input[type=checkbox]').count()===0&&await page.locator('.nw-space-canvas').count()===0);const jev=await page.evaluate(()=>window.fixture.trace.calls.filter(call=>call.mode==='jev').length);await nav(page,'Conversation map').click();check('Opening conversation map stays local without Jev evaluation',await page.evaluate(before=>window.fixture.trace.calls.filter(call=>call.mode==='jev').length===before,jev)&&await btn(page,'Analyze conversation flow').count()===0);await nav(page,'Chat').click();
  await page.setViewportSize({width:320,height:900});await noOverflow(page,'sidebar 320px');await shot(page,'sidebar-320-light');await mount(page,'workspace');await noOverflow(page,'graph 320px');check('Narrow desktop graph stays separate from the chat composer',await page.locator('[data-focus-id=question]').count()===0);await shot(page,'workspace-320-light');
  await language(page);check('Application UI remains English-only',report.languageViolations.length===0);check('No browser runtime errors',report.pageErrors.length===0,report.pageErrors);check('No external requests downloads or popups',report.externalRequests.length===0&&report.downloads.length===0&&report.popups.length===0);

}
(async()=>{let server,browser;try{const allowlist=new Set(['tests/ui-fixture.html','styles.css',...fs.readdirSync(path.join(project,'src')).filter(file=>file.endsWith('.mjs')).map(file=>'src/'+file),'src/providers/claude-login-url.mjs','src/providers/codex-login-url.mjs','src/providers/ollama-embeddings.mjs','src/providers/jev.mjs']);server=http.createServer((request,response)=>{const pathname=new URL(request.url,'http://127.0.0.1').pathname.slice(1);if(!allowlist.has(pathname)){response.writeHead(404);response.end();return;}response.setHeader('Cache-Control','no-store');response.setHeader('Content-Type',pathname.endsWith('.html')?'text/html; charset=utf-8':pathname.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');response.end(fs.readFileSync(path.join(project,pathname)));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--disable-gpu']});const context=await browser.newContext({viewport:{width:1200,height:800}});const page=await context.newPage();await attachKnowledgeBridge(page);await run(page,origin);report.passed=true;}catch(error){report.passed=false;report.failure=String(error);process.exitCode=1;}finally{if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));report.finishedAt=new Date().toISOString();report.productionModulesAtEnd=Object.fromEntries(tracked.map(file=>[file,digest(file)]));report.sourceChangedDuringRun=JSON.stringify(report.productionModules)!==JSON.stringify(report.productionModulesAtEnd);fs.writeFileSync(path.join(output,'workspace-ui-report.json'),JSON.stringify(report,null,2));process.stdout.write(JSON.stringify({passed:report.passed,checks:report.checks.length,failure:report.failure,screenshots:report.screenshots.length,sourceChangedDuringRun:report.sourceChangedDuringRun,report:path.join(output,'workspace-ui-report.json')},null,2));}})();
